### ISSUE TITLE
Build Succeeds but app crashed on iOS

### ISSUE THREAD

**Issue by prameetc** [mieszko4/react-native-zoom-us#1]
I followed all the steps as mentioned and cleaned and built the project. Though the build succeeds on Xcode, the app crashes while opening.

**Comment by mieszko4** [comment]
Without some logs it will be hard for me to figure out the problem.
Does the demo build for you https://github.com/mieszko4/react-native-zoom-us-test?

**Comment by prameetc** [comment]
With the demo build, I get this error on Xcode 

`ld: library not found for -lstdc++.6.0.9`

**Comment by mieszko4** [comment]
What version of xcode do you use?
I was testing that with `9.4` and it works for me.
If you are using xcode 10 I believe this should solve your problem https://stackoverflow.com/a/52422621/3042620

**Comment by prameetc** [comment]
@mieszko4 Awesome! It works now.

**Comment by prameetc** [comment]
Ok, this is the issue I was actually facing. After the build succeeds, the simulator starts and while building it crashes. 

I get this error on xcode console.

```dyld: Library not loaded: /usr/lib/libstdc++.6.dylib
  Referenced from: /Users/prameet/Library/Developer/CoreSimulator/Devices/46BF5922-9EBC-45C9-8839-06E14E6A21E5/data/Containers/Bundle/Application/54C6A164-9728-4C70-A5C6-CB735C177E6A/ZoomUsTest.app/Frameworks/MobileRTC.framework/MobileRTC
  Reason: no suitable image found.  Did find:
	/usr/lib/libstdc++.6.dylib: mach-o, but not built for iOS simulator```

**Comment by prameetc** [comment]
I think this tries to solve that issue

https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9

**Comment by mieszko4** [comment]
:thinking:  I am not sure, have you tried to run and build it for real device?

**Comment by prameetc** [comment]
@mieszko4 I cannot build on my iPhone due to code signing issues. My device is not added to your team.

**Comment by mieszko4** [comment]
Try to choose your team and code signing.

**Comment by prameetc** [comment]
Yeah doing that

**Comment by prameetc** [comment]
Do we need to install Zoom SDK seperately? I get this error when I call the `ZoomUs.initialize` function 

```Error: ZoomSDK has not been initialized successfully
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:392)
    at MessageQueue.js:128
    at MessageQueue.__guard (MessageQueue.js:291)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:127)
    at debuggerWorker.js:72```

**Comment by mieszko4** [comment]
nope. no need for extra install. if you followed all steps carefully you shoupd be able to run it.
note that zoom sdk does not work for Android emulator

**Comment by mieszko4** [comment]
thnx @prameetc If you think that might be relevant please summarize where you got stucked at and how you solved it so it can be useful for others :)

**Comment by KawaljeetSBagga** [comment]
> Ok, this is the issue I was actually facing while using the package. After the build succeeds, the simulator starts and while building it crashes.
> 
> I get this error on xcode debugging console.
> 
> Looks like it's connected to that same file `libstdc++.6`. Any workarounds?
> 
> ```
>   Referenced from: /Users/prameet/Library/Developer/CoreSimulator/Devices/46BF5922-9EBC-45C9-8839-06E14E6A21E5/data/Containers/Bundle/Application/54C6A164-9728-4C70-A5C6-CB735C177E6A/ZoomUsTest.app/Frameworks/MobileRTC.framework/MobileRTC
>   Reason: no suitable image found.  Did find: 
> /usr/lib/libstdc++.6.dylib: mach-o, but not built for iOS simulator
> ```

@mieszko4  I have followed the steps you mentioned and get the same error as this. Form this it seems that it won't work on an emulator. But, I have pointed to the MobileRTC.framework and MobileRTC.bundle downloaded for "all" versions from zoom official releases which says that the "all" version would work on both physical device and the simulator. Need some more insight on what's happening here.

**Comment by mieszko4** [comment]
Right, sorry, I haven't updated this package for a long time so there could be a lot of reasons: different version of xcode is one of them.
I am really trying to find some time to finally take a good look on this and update the package, rn, and zoom sdks.
I really hope I will find some time this weekend to do that..

**Comment by KawaljeetSBagga** [comment]
> Do we need to install Zoom SDK seperately? I get this error when I call the `ZoomUs.initialize` function in Android. Just confirming, the AppKey and AppSecret goes inside the initialize function right? Not the SDK Key and Secret.
> 
> ```
> Error: ZoomSDK has not been initialized successfully
>     at createErrorFromErrorData (NativeModules.js:146)
>     at NativeModules.js:95
>     at MessageQueue.__invokeCallback (MessageQueue.js:392)
>     at MessageQueue.js:128
>     at MessageQueue.__guard (MessageQueue.js:291)
>     at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:127)
>     at debuggerWorker.js:72```
> ```

@prameetc hey how were you able to overcome this? Can you please share?

**Comment by KawaljeetSBagga** [comment]
Ok guys. I have also made it running successfully and flawlessly on both iOS simulator(iPhone 11) and actual android physical device(One plus 7T). Steps to remember/re-check if you get stuck:

First of all: 
***READ AND UNDERSTAND THE ZOOM OFFICIAL DOCS***
Android - [https://marketplace.zoom.us/docs/sdk/native-sdks/android]
iOS - [https://marketplace.zoom.us/docs/sdk/native-sdks/iOS]

 **iOS** : 
1. I used the "All" versions to test it on an iOS simulator, you will need to further go ahead and replace it with the "Source" version for getting it approved by Apple. You can find these versions here - [https://github.com/zoom/zoom-sdk-ios/releases]

2. After following the mentioned steps properly, I got an error as below: 

>  ...
Referenced from: /Users/Kawaljeet/Library/Developer/CoreSimulator/Devices/46BF5922-9EBC-45C9-8839-06E14E6A21E5/data/Containers/Bundle/Application/54C6A164-9728-4C70-A5C6-CB735C177E6A/ZoomUsTest.app/Frameworks/MobileRTC.framework/MobileRTC
  Reason: no suitable image found.  Did find: 
/usr/lib/libstdc++.6.dylib: mach-o, but not built for iOS simulator

I resolved it just removing this library. (Not sure why we need it).
Thats all in my case for iOS. I got it running after this.

**Android**:
After following the mentioned steps properly, I got a crash on the device saying:

> ...
couldn’t find “libzoom_stlport.so”
I resolved it using this link:[(https://stackoverflow.com/questions/42679046/gradle-project-dependency-with-multidex)]
Thats all in my case for Android. I got it running after this.

My development environment is as below:
XCode - 11.4
Android studio - 3.6.1
React native - 0.62

Hope this saves someone's struggle and time someday.
Don't try on giving up on this package, it works flawlessly.
Thank you for the awesome package @mieszko4

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
