### ISSUE TITLE
Zoom video doesn't rotate when screen is rotated to Landscape (on iOS)

### ISSUE THREAD

**Issue by jayantishere** [mieszko4/react-native-zoom-us#101]
Please check the 2 video files attached to understand the behaviour. Request you to help in this regard.

https://user-images.githubusercontent.com/6203087/131124982-66381338-a59c-44f4-9c93-dbee30593091.mp4

https://user-images.githubusercontent.com/6203087/131125009-1cf8a994-2ae7-47db-aafa-a8259545f163.mp4

**Comment by VijaySharma12** [comment]
Please Give me sample code.

**Comment by mieszko4** [comment]
It works with newest 6.1.1 that has 5.7 iOS SDK
Sample app: https://github.com/mieszko4/react-native-zoom-us-test

**Comment by jayantishere** [comment]
Thanks! We'll check and get back in case we have concerns.

**Comment by Niranjankr0** [comment]
This issue again open in latest version 6.6.1
