### ISSUE TITLE
I can't join meeting affter reload ios app. joinMeeting, joinMeetingResult=152. How can i fix it, please

### ISSUE THREAD

**Issue by haivieted** [mieszko4/react-native-zoom-us#102]

**Comment by haivieted** [comment]
joinMeeting, joinMeetingResult=152. How can i fix it, please

**Comment by hans00** [comment]
Error code 152 is `MobileRTCMeetError_InAnotherMeeting`

It means you haven't leave meeting before reload.

**Comment by hans00** [comment]
The full error code define see this.
https://marketplacefront.zoom.us/sdk/meeting/ios/_mobile_r_t_c_constants_8h_source.html

`joinMeetingResult` is `MobileRTCMeetError`

**Comment by haivieted** [comment]
> Error code 152 is `MobileRTCMeetError_InAnotherMeeting`
> 
> It means you haven't leave meeting before reload.

I have had quit from meeting before. Then i reloaded the app by shaking ios device -> cause the issue

**Comment by mieszko4** [comment]
:thinking: Seems like zoom-sdk related problem... Does it happen on android?

**Comment by haivieted** [comment]
> 🤔 Seems like zoom-sdk related problem... Does it happen on android?

Android work perfectly. Zoom SDK android is 5.7. Zoom SDK IOS is 5.5

**Comment by mieszko4** [comment]
I will be merging/releasing iOS update, soon (https://github.com/mieszko4/react-native-zoom-us/pull/112)

**Comment by mieszko4** [comment]
6.1.1 has newest iOS update, too. verify with the new version please
