### ISSUE TITLE
How can i hide zoom button on top bar

### ISSUE THREAD

**Issue by haivieted** [mieszko4/react-native-zoom-us#106]
How can i hide zoom button on top bar
![IMG_6F2F6FDF6488-1](https://user-images.githubusercontent.com/70926688/132082199-493ef2de-e7f4-4e19-bdc3-9131c6184ffc.jpeg)

**Comment by amdrade** [comment]
Try pass `noBottomToolbar` on `joinMeeting`

**Comment by ashuOxit** [comment]
You can also use `noTextMeetingId` to hide the zoom title from toolbar

**Comment by mieszko4** [comment]
Note that these params are android-only currently. 
I will close that now. Feel free to reopen.
