### ISSUE TITLE
How can i hide driving mode in android ?

### ISSUE THREAD

**Issue by ashuOxit** [mieszko4/react-native-zoom-us#110]
I tried to use `noDrivingMode` but nothing happens

**Comment by mieszko4** [comment]
That's not implemented at the moment. Needs to be uncommented from:
https://github.com/mieszko4/react-native-zoom-us/blob/c69f0684d19b9723a4a3d6ca4f13d9081ad1a7f9/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java#L275

And added to `index.ts`

Feel free to submit a pr

**Comment by ashuOxit** [comment]
@mieszko4 i do have a query regarding the ios side. we have some options in android like noShare,noTextMeetingId, etc are they will work after the current open PR is merged?

**Comment by mieszko4** [comment]
Just a note: for `iOS` this is a blocker https://github.com/mieszko4/react-native-zoom-us/issues/113 for using `driveModeDisabled()`
(https://zoom.github.io/zoom-sdk-ios/interface_mobile_r_t_c_meeting_settings.html#ab80eb108ad909bd832eef97e46124865)

**Comment by mieszko4** [comment]
I've added the following options to android:
```
noDrivingMode
noDisconnectAudio
noRecord
noUnmuteConfirmDialog
noWebinarRegisterDialog
noChatMsgToast
```

Done in 6.1.3
