### ISSUE TITLE
Exception thrown when settings are used and language is not set

### ISSUE THREAD

**Issue by pmogollons** [mieszko4/react-native-zoom-us#117]
https://github.com/mieszko4/react-native-zoom-us/blob/caa9902c7a0770fbc553ccd634752a1a0cc18b77/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java#L117

It happens on the split because language is not checked for null.

**Comment by mieszko4** [comment]
The error is actually here: https://github.com/mieszko4/react-native-zoom-us/blob/caa9902c7a0770fbc553ccd634752a1a0cc18b77/index.ts#L45
