### ISSUE TITLE
VideoView component not passing smoke test

### ISSUE THREAD

**Issue by pmogollons** [mieszko4/react-native-zoom-us#118]
This is probably caused by the updated sdk version after this feature was added.

@hans00 Do you have any idea what could be causing this issue in the latest version.

![image](https://user-images.githubusercontent.com/32210050/133137518-51af4c70-f4ce-4bbb-a4df-800aa571d241.png)

**Comment by pmogollons** [comment]
I can confirm that it works on v5.12.1 so is most probably a change in the SDK version.

**Comment by mieszko4** [comment]
Could you paste example of your code where you use `VideoView` so I can try it myself?

**Comment by mieszko4** [comment]
Nevermind, I can reproduce this -> example https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx when `const enableCustomizedMeetingUI = true;`

**Comment by mieszko4** [comment]
Seems related https://devforum.zoom.us/t/error-inflating-class-us-zoom-sdk-mobilertcshareview/40945/14

**Comment by mieszko4** [comment]
I was playing a bit with it. If I render the component after triggering meeting joining then there is no error.
So as a workaround we can deal with this on js side.
I will update the example later.

**Comment by pmogollons** [comment]
Interesting, ill try that on my side too. Thanks.

**Comment by mieszko4** [comment]
This is a how I did that https://github.com/mieszko4/react-native-zoom-us-test/commit/aac35f9e69bec19ccffe73f360bfc0a52452a6a8

However, it is not perfect. For example I could not use `Leave Meeting` because of error regarding calling it from another thread

**Comment by pmogollons** [comment]
@mieszko4 I think this will solve the issue if we docment it. Still has other bugs I will open other issues.

**Comment by mieszko4** [comment]
Thnx @pmogollons I agree documenting should be helpful. But the issue is still in java. There should be some condition to check not to mount `VideoView` if not ready.

**Comment by mieszko4** [comment]
I've adjusted the test app and updated the lib with some fixes.
Now if you enable `const enableCustomizedMeetingUI = true;` https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L109 the smoke test is passing with `leaveMeeting`
