### ISSUE TITLE
TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by gHashTag** [mieszko4/react-native-zoom-us#12]
I did everything according to the instructions, but this error flies.
<img width="539" alt="Снимок экрана 2020-05-02 в 11 37 50" src="https://user-images.githubusercontent.com/6774813/80859397-5bedfe80-8c69-11ea-9a5f-49af2501c782.png">

**Comment by andywall66** [comment]
Same issue here - iOS. Believe it's the same as https://github.com/mieszko4/react-native-zoom-us/issues/10

With iOS:
- xCode 11.4.1
- iOS 13.4.1
- React Native 0.61.5
- Installed RNZoomUS via podspec
- CocoaPods 1.9.1
- Did manual steps
- Builds without errors
- JS import works

...but ZoomUS is undefined. Not in Native Modules?

**Comment by amdrade** [comment]
try this: [https://github.com/mieszko4/react-native-zoom-us/issues/10#issuecomment-636580013](https://github.com/mieszko4/react-native-zoom-us/issues/10#issuecomment-636580013)

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.

**Comment by Ahmed-free** [comment]
![image](https://user-images.githubusercontent.com/100868614/190082248-b43ef7a1-2b2e-447a-947f-3a3b1c8cf427.png)

Hi the I am facing the same error again , now on react native 0.69

`"dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "axios": "^0.27.2",
    "expo": "~46.0.7",
    "expo-av": "~12.0.4",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.5",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.4",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-webview": "^11.23.1",
    "react-native-zoom-us": "^6.14.1"
  }`

any help ?

**Comment by mieszko4** [comment]
Have you tried https://github.com/mieszko4/react-native-zoom-us/issues/12#issuecomment-636581757 suggestion?
Also please reopen the issue or create a new one. It is hard to track conversations on closed issues.
