### ISSUE TITLE
[iOS] How to hide meeting information?

### ISSUE THREAD

**Issue by haivieted** [mieszko4/react-native-zoom-us#120]
![IMG_C520C26B2D3D-1](https://user-images.githubusercontent.com/70926688/133227827-54864f5b-f3bc-42ca-b3d1-ca1ce3e0241c.jpeg)

I have try to hide zoom meeting information by implement this code but unluckily it hide breakout zoom too, anyone can help me?
MobileRTCMeetingSettings *settings = [[MobileRTC sharedRTC] getMeetingSettings];
[settings setTopBarHidden:YES];

**Comment by imshreyansh** [comment]
+1

**Comment by mieszko4** [comment]
It looks like that would be `meetingTitleHidden` native setting of https://marketplacefront.zoom.us/sdk/meeting/ios/interface_mobile_r_t_c_meeting_settings.html#a22e7951e826ca913b3e1dc5427db2e1c

However, in order for it to function https://github.com/mieszko4/react-native-zoom-us/issues/113 must be implented first

**Comment by mieszko4** [comment]
Looks like https://github.com/mieszko4/react-native-zoom-us/pull/65#issuecomment-1207101446 could be solution to this issue.
