### ISSUE TITLE
How can i hide chat option in android from more settings?

### ISSUE THREAD

**Issue by ashuOxit** [mieszko4/react-native-zoom-us#122]
I want to hide the chat option from more options and also want to hide some info from meeting info is there are some setting by which I can do this

**Comment by mieszko4** [comment]
To disable the chat I believe you can do it during the meeting creation on the zoom.us admin - https://support.zoom.us/hc/en-us/articles/115004809306-Controlling-and-disabling-in-meeting-chat
I do not see such option on native android Zoom SDK.

Other join params, e.g. `noShare` you can find here:
https://github.com/mieszko4/react-native-zoom-us/blob/f7eb57860f41e75cf94fa2acb84556e147270fa5/index.ts#L88-L118

You may also build your own custom view  - use `const enableCustomizedMeetingUI = true;` of the test app https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L109 to play with it
