### ISSUE TITLE
Ver 6.1.5 - Android build failed

### ISSUE THREAD

**Issue by haivieted** [mieszko4/react-native-zoom-us#123]
When i update react-native-zoom-us to version 6.1.5 then android build failed with an exception
react-native: 0.62.2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.flexbox.AlignContent found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.AlignItems found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.AlignSelf found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexContainer found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexDirection found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexItem found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexLine found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexWrap found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxHelper found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxHelper$1 found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxHelper$FlexLinesResult found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxHelper$Order found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxItemDecoration found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxLayout found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)
  Duplicate class com.google.android.flexbox.FlexboxLayout$DividerMode found in modules flexbox-2.0.1-runtime.jar (com.google.android:flexbox:2.0.1) and flexbox-3.0.0-runtime.jar (com.google.android.flexbox:flexbox:3.0.0)

**Comment by haivieted** [comment]
I resolved this by remove this line  implementation 'com.google.android:flexbox:2.0.1'

**Comment by mieszko4** [comment]
:thinking: It is working for me - but I was using react-native 0.64
