### ISSUE TITLE
Couldn't able to run app in android 

### ISSUE THREAD

**Issue by selvakumarmg** [mieszko4/react-native-zoom-us#124]
What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android:flexbox:2.0.1.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.google.android:flexbox:2.0.1.
         > Could not get resource 'https://google.bintray.com/flexbox-layout/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom'.
            > Could not HEAD 'https://google.bintray.com/flexbox-layout/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.exoplayer:exoplayer-core:2.12.3.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.google.android.exoplayer:exoplayer-core:2.12.3.
         > Could not get resource 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-core/2.12.3/exoplayer-core-2.12.3.pom'.
            > Could not GET 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-core/2.12.3/exoplayer-core-2.12.3.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.exoplayer:exoplayer-ui:2.12.3.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.google.android.exoplayer:exoplayer-ui:2.12.3.
         > Could not get resource 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-ui/2.12.3/exoplayer-ui-2.12.3.pom'.
            > Could not GET 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-ui/2.12.3/exoplayer-ui-2.12.3.pom'. Received status code 403 from server: Forbidden What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android:flexbox:2.0.1.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.google.android:flexbox:2.0.1.
         > Could not get resource 'https://google.bintray.com/flexbox-layout/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom'.
            > Could not HEAD 'https://google.bintray.com/flexbox-layout/com/google/android/flexbox/2.0.1/flexbox-2.0.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.exoplayer:exoplayer-core:2.12.3.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.google.android.exoplayer:exoplayer-core:2.12.3.
         > Could not get resource 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-core/2.12.3/exoplayer-core-2.12.3.pom'.
            > Could not GET 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-core/2.12.3/exoplayer-core-2.12.3.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.exoplayer:exoplayer-ui:2.12.3.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.google.android.exoplayer:exoplayer-ui:2.12.3.
         > Could not get resource 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-ui/2.12.3/exoplayer-ui-2.12.3.pom'.
            > Could not GET 'https://google.bintray.com/flexbox-layout/com/google/android/exoplayer/exoplayer-ui/2.12.3/exoplayer-ui-2.12.3.pom'. Received status code 403 from server: Forbidden

**Comment by haivieted** [comment]
https://github.com/mieszko4/react-native-zoom-us/blob/master/docs/UPGRADING.md
Follow this step, friend.

**Comment by zvs001** [comment]
You need to add repositories to your root build.gradle file.
I don't know which exactly are required for these libs. Just add all of them

```
allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
        maven { url "https://www.jitpack.io" }
    }
}
```

**Comment by mieszko4** [comment]
I will close this now, feel free to reopen
