### ISSUE TITLE
Test app crashes when un muting audio or video

### ISSUE THREAD

**Issue by pmogollons** [mieszko4/react-native-zoom-us#125]
Unfortunately when unmuting audio or video in the test app it crashes and it doesnt seem to leave any trace in catlog.

This is probably related to the update of the android SDK.

**Comment by pmogollons** [comment]
I was able to identify the issue cause, onUserStatusChanged is not called from the main thread.

![image](https://user-images.githubusercontent.com/32210050/134577288-cff809e3-b319-42bf-a3ae-09f42a7fb676.png)

**Comment by mieszko4** [comment]
Is that related to https://github.com/mieszko4/react-native-zoom-us/pull/126?
And does it happen when using Custom View?

**Comment by pmogollons** [comment]
I thought the same but no, I just found a solution, not sure is the best one. I had to wrap the muteMyAudio and muteMyVideo calls in runOnUiThread like this.

Do you think this could be a good solution or do you have a suggestion?

```javascript
  UiThreadUtil.runOnUiThread(new Runnable() {
      @Override
      public void run() {
        final InMeetingVideoController videoController = zoomSDK.getInMeetingService().getInMeetingVideoController();

        MobileRTCSDKError result = videoController.muteMyVideo(muted);

        if (result == MobileRTCSDKError.SDKERR_SUCCESS) {
          promise.resolve(videoController.isMyVideoMuted();
        } else {
          promise.reject("ERR_ZOOM_MEETING_CONTROL", "Mute my video error, status: " + result.name());
        }
      }
    });
```

**Comment by pmogollons** [comment]
Well this works with no issue after some tests, now I found out that for the audio status listener to work correctly we need to update to the latest version of the SDK.

https://marketplace.zoom.us/docs/changelog#publications/android-meeting-sdk-v5-7-1-1268-hotfix

**Comment by mieszko4** [comment]
I've created an issue for upgrading skd https://github.com/mieszko4/react-native-zoom-us/issues/132

**Comment by mieszko4** [comment]
> I thought the same but no, I just found a solution, not sure is the best one. I had to wrap the muteMyAudio and muteMyVideo calls in runOnUiThread like this.
> 
> Do you think this could be a good solution or do you have a suggestion?
> 
> ```js
>   UiThreadUtil.runOnUiThread(new Runnable() {
>       @Override
>       public void run() {
>         final InMeetingVideoController videoController = zoomSDK.getInMeetingService().getInMeetingVideoController();
> 
>         MobileRTCSDKError result = videoController.muteMyVideo(muted);
> 
>         if (result == MobileRTCSDKError.SDKERR_SUCCESS) {
>           promise.resolve(videoController.isMyVideoMuted();
>         } else {
>           promise.reject("ERR_ZOOM_MEETING_CONTROL", "Mute my video error, status: " + result.name());
>         }
>       }
>     });
> ```

I am not that good with android but I believe that's the correct pattern

**Comment by mieszko4** [comment]
One more note regarding running thing in the main thread:
On android Zoom SDK page (https://marketplace.zoom.us/docs/sdk/native-sdks/android/mastering-zoom-sdk/sdk-initialization) it says:
> Please note that SDK initialization and all API call must run in Main Thread.
