### ISSUE TITLE
ZoomUs.initialize not working

### ISSUE THREAD

**Issue by ChauVV** [mieszko4/react-native-zoom-us#128]
i try the test project: https://github.com/mieszko4/react-native-zoom-us-test

but func ZoomUs.initialize not work,
i try with sdkJwtToken is not work,
try with clientKey & clientSecret still not work,

dont have response or error.
please help.

**Comment by mieszko4** [comment]
> try with clientKey & clientSecret still not work,

Please not that you need `sdkKey` and `sdkSecret` secret. It is different than "clientKey & clientSecret"
