### ISSUE TITLE
Throws error when user tries to join using webinarToken 

### ISSUE THREAD

**Issue by Md-Mudassir47** [mieszko4/react-native-zoom-us#129]
I tried you example repo [react-native-zoom-us-test]( https://github.com/mieszko4/react-native-zoom-us-test ). when i join the meeting without passing the webinarToken it works fine but when i pass the token it throws the below error.

![err1](https://user-images.githubusercontent.com/85115578/134521812-1247e236-2d07-4ab3-ad15-dd4ab7fb14ec.jpeg)
![err2](https://user-images.githubusercontent.com/85115578/134521772-85788716-887d-4c0c-ab24-6b78956a2e78.jpeg)

in console it shows this error  `ERROR  [Error: Error: 100, internalErrorCode=0]`

```js
  const joinMeeting = async () => {
    try {
      const joinMeetingResult = await ZoomUs.joinMeeting({
        autoConnectAudio: true,
        userName: 'Wick',
        meetingNumber: '83321333122' || '',
        noShare: true,
        webinarToken:
          'vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_9zofM9WZQYGWMFBQLcC4ow',
      });

      console.log({joinMeetingResult});
    } catch (e) {
      Alert.alert('Error', 'Could not execute joinMeeting');
      console.error(e);
    }
  };
```

**Comment by mieszko4** [comment]
There seemed to be a bug. try with newest version of this lib please

**Comment by Md-Mudassir47** [comment]
> There seemed to be a bug. try with newest version of this lib please

Thank You. Will try it out

**Comment by mieszko4** [comment]
Sure, you can also send me a fresh  `webinarToken` so I can check it myself

**Comment by Md-Mudassir47** [comment]
> Sure, you can also send me a fresh `webinarToken` so I can check it myself

the above token & webinar ID in the code is still valid till 30th Sep.. Please use it

**Comment by mieszko4** [comment]
For reference: that would be link: https://us02web.zoom.us/w/83321333122?tk=vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_9zofM9WZQYGWMFBQLcC4ow
I can join using this link with no problem.


However, I cannot join when using it with `react-native-zoom-us-test` app.
I am getting the same `Error Code: 124`
I've tried to enter the params directly into:
```java
/*
params:
params.webinarToken = vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_9zofM9WZQYGWMFBQLcC4ow
params.meetingNo = 83321333122
params.displayName = Wick

no options
opts = JoinMeetingOptions opts = new JoinMeetingOptions();
*/
int joinMeetingResult = meetingService.joinMeetingWithParams(reactContext.getCurrentActivity(), params, opts);
```
Still no luck.


So my guess is that it does not work because I am using `sdkKey` and `sdkSecret` to initialize the app of the Basic account. And Basic account does not support webinars.

@Md-Mudassir47 Could you try that yourself with your sdk (Since you've created webinars that must mean your `sdkKey` and `sdkSecret` should support webinar)? Use the newest version of `react-native-zoom-us` lib

**Comment by Md-Mudassir47** [comment]
@mieszko4 I tried it with my sdk & it works fine on iOS no issue even with the token, but doesn't work on android.. it still throws the same error & if I were to remove the token then it works on android but asks the user for username & email every-time.. though the username gets auto-filled but email field stays empty.. so is there a way to pass email just like username to the fields?

**Comment by mieszko4** [comment]
I confirm that on iOS there is no problem. I will take a look on this again on android

**Comment by mieszko4** [comment]
I've finally found the issue.
Your webinar token is not correct:
```
vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_9zofM9WZQYGWMFBQLcC4ow
```


Note `&uuid=` extra part
The correct token is:

```
vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

I guess on iOS it was working because iOS has different implementation of how to parse the token.

**Comment by Md-Mudassir47** [comment]
> I've finally found the issue. Your webinar token is not correct:
> 
> ```
> vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_9zofM9WZQYGWMFBQLcC4ow
> ```
> 
> Note `&uuid=` extra part The correct token is:
> 
> ```
> vLk2cdfRfUOC6FXNvu7fuRKHeWhAPnLA2tWdgcSd0pk.DQMAAAATZlalghZOMExWdG9jTFJNT0dLYkFmaFlWSmR3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
> ```
> 
> I guess on iOS it was working because iOS has different implementation of how to parse the token.

That's indeed a great catch, Thank you so much for all your hard work!
