### ISSUE TITLE
Error: startMeeting, errorCode=99

### ISSUE THREAD

**Issue by rananajam1** [mieszko4/react-native-zoom-us#13]
I get this error when ZoomUs.startMeeting event is fired. Can someone please help?

**Comment by nazmultanvir** [comment]
errorCode=99 is for ZOOM_ERROR_DEVICE_NOT_SUPPORTED, so i like this problem is happening emulator. Let me know if you have found any good solution then this.

**Comment by rananajam1** [comment]
@nazmultanvir  Have you tried building this on a real device? And any progress with this?

**Comment by zvs001** [comment]
This error means: Invalid Arguments.

**Comment by RahulRijhwani** [comment]
I faced same issue I have installed 
    "react-native-zoom-us": "^5.3.1"

any suggestion ?

**Comment by mieszko4** [comment]
Based on https://marketplace.zoom.us/docs/sdk/native-sdks/ionic/resource/error-codes `99` means `ZOOM_ERROR_DEVICE_NOT_SUPPORTED`.
On what device do you test this?
