### ISSUE TITLE
onUserAudioStatusChanged returns incorrect userId

### ISSUE THREAD

**Issue by pmogollons** [mieszko4/react-native-zoom-us#131]
This is caused by the version of the SDK's we are using right now, updating to the latest SDK will fix the issue. Same for onShareActiveUser listener.

https://marketplace.zoom.us/docs/changelog#publications/android-meeting-sdk-v5-7-1-1268-hotfix

**Comment by mieszko4** [comment]
6.3.0 released with newest version of android and ios sdk
