### ISSUE TITLE
Can't join as the meeting host

### ISSUE THREAD

**Issue by drewklein20** [mieszko4/react-native-zoom-us#135]
I'm a bit confused with the separate functions "startMeeting" and "joinMeeting". I'm currently only using the "joinMeeting" function but this is joining as a regular participant and not the host. Do I need to call "startMeeting" with a zak in order to join as the meeting host? To add, If I try using the startMeeting function with a zak, I'm prompted for the password for the meeting.

Build info: (testing on iOS)
"react": "16.13.1",
"react-native": "0.64.2",
"react-native-zoom-us": "^6.1.5"

**Comment by mieszko4** [comment]
Yes, for "joining" meeting as the host you need to use `startMeeting` with `zoomAccessToken`

Please see https://devforum.zoom.us/t/non-login-user-host-meeting-userid-accesstoken-zoomaccesstoken-zak/18720/3 for the discussion. And let me know if that helps you.

**Comment by drewklein20** [comment]
Not sure if this is the expected experience but when I call `startMeeting` with a zak, I am prompted for a meeting password. In which case, it still does not join as the meeting host. (I am testing on iOS)

**Comment by mieszko4** [comment]
You are probably not using the correct token then.
Anyway, I've took improved the test app to show which data should be passed to start meeting.
I am fetching user through zoom API and then use the user's personal meeting id (`.pmi`) and its `zak` token
The instructions on how to achieve this are in:
https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L33-L41

You can also see the implementation in this pr https://github.com/mieszko4/react-native-zoom-us-test/pull/31/files

**Comment by drewklein20** [comment]
@mieszko4  Thanks a ton for all your help and hard work!!

I have no trouble obtaining a zak from the API.
I was able to join the meeting as the host. I was mistakenly using the user's email as the userId (since the zoom api allows you to do this I guess I figured this would as well). Once I changed it to the actual Id of the user, it joined as the host but it still made me enter the meeting password. Is there anyway the startMeeting function could be passed the meeting password similar to the joinMeeting?

Isn't the PMI used for something different? I'm not sure using it in this context is what it's intended for.

**Comment by drewklein20** [comment]
Okay, figured it out.. Sorry for being a pain! I was missing the `type=zak` query param in my api request when getting the `zak`!

**Comment by mieszko4** [comment]
Sure, no worries. It was my initial mistake, too :)

**Comment by mieszko4** [comment]
Just for reference:

I've used `pmi` only as a quick demo here. I tried with other meeting id the owner of which is my user and it worked.

So I guess what's important here is that the user for which you get `zak` must have permission to start the specific meeting.
