### ISSUE TITLE
startZoomScreenShare is not implemented correctly

### ISSUE THREAD

**Issue by pmogollons** [mieszko4/react-native-zoom-us#140]
https://marketplace.zoom.us/docs/sdk/native-sdks/android/mastering-zoom-sdk/in-meeting-function/customized-meeting-ui/share

Before we start sharing the screen we need permission from android system, when you get permission you call startShareScreenSession with the intent data, and on onShareActiveUser we startShareScreenContent.

Im having issues with the activity result as creating that in the module file wont get the method called.

@mieszko4 any ideas on how can we get the activity result called?

Also we might need to implement a service for some version of android [docs](https://marketplace.zoom.us/docs/sdk/video/android/advanced/screen-share)

**Comment by mieszko4** [comment]
This got broken when introducing `UiThreadUtil.runOnUiThread(` in https://github.com/mieszko4/react-native-zoom-us/pull/137 
The current released version handles screen sharing correctly (Tried with non custom view)

**Comment by mieszko4** [comment]
So this `UiThreadUtil.runOnUiThread(` needs to be reverted.
For custom view I am getting `Error: Start share screen error, status: SDKERR_WRONG_USEAGE` - so this should be the focus of fixing it

**Comment by mieszko4** [comment]
> This got broken when introducing `UiThreadUtil.runOnUiThread(` in #137 The current released version handles screen sharing correctly (Tried with non custom view)

Actually, nevermind, it works with these `UiThreadUtil.runOnUiThread` for me. I just had to fix some compile errors (adding `final` keywords)

It only does not work for me when using Custom View.


@paulo-mogollon Could you provide exact steps how to reproduce this?

**Comment by pmogollons** [comment]
You are right, the changes in the docs are only required for custom ui, so we should use different methods or check if custom ui is used.

**Comment by mieszko4** [comment]
`v6.4.0`, thnx @pmogollons !
I've also updated the test app with screen sharing button for android custom view - https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L61
