### ISSUE TITLE
Screen shared by other users is not being showed when using custom ui

### ISSUE THREAD

**Issue by pmogollons** [mieszko4/react-native-zoom-us#142]
Im using this snippet and it still doesnt show, even when the only view is the active-share

```javascript
<ZoomUsVideoView
  style={styles.container}
  layout={[
    // {
    //   kind: 'active',
    //   x: 0,
    //   y: 0,
    //   width: 1,
    //   height: 0.5,
    //   border: false,
    //   showUsername: true,
    //   showAudioOff: true,
    // },
    // active speaker's share // TODO: Screen share is not being showed
    {
      kind: 'active-share',
      x: 0,
      y: 0,
      width: 1,
      height: 1,
      border: true,
    },
  ]}
/>
```

**Comment by mieszko4** [comment]
:thinking: It is working for me - see https://github.com/mieszko4/react-native-zoom-us-test/commit/27ecd8bc642678fe3dccb385b1ceae884c54504b

However, I cannot show both screen share an video at the same time

**Comment by pmogollons** [comment]
Ill test it later on the test app and later on mine to check where the issue could be. Thanks.

**Comment by pmogollons** [comment]
Yes, with some changes in my code I got it working. Probably I was still rendering the 2 views at the same time.
