### ISSUE TITLE
Cannot pass meeting password to zoom sdk

### ISSUE THREAD

**Issue by KawaljeetSBagga** [mieszko4/react-native-zoom-us#15]
Hey @mieszko4, seems like we can only join meeting with display name and meeting id as of now, and if there's a password required, then the user has to enter it manually. I have added a method on both the platforms iOS and android inside your package which are as follows:
**iOS**:

> RCT_EXPORT_METHOD(
  joinMeetingWithPassword: (NSString *)displayName
  withMeetingNo: (NSString *)meetingNo
  withPassword: (NSString *)password
  withResolve: (RCTPromiseResolveBlock)resolve
  withReject: (RCTPromiseRejectBlock)reject
)
{
  @try {
    meetingPromiseResolve = resolve;
    meetingPromiseReject = reject;
    MobileRTCMeetingService *ms = [[MobileRTC sharedRTC] getMeetingService];
    if (ms) {
      ms.delegate = self;
      NSDictionary *paramDict = @{
        kMeetingParam_Username: displayName,
        kMeetingParam_MeetingNumber: meetingNo,
        kMeetingParam_MeetingPassword: password
      };
      MobileRTCMeetError joinMeetingResult = [ms joinMeetingWithDictionary:paramDict];
      NSLog(@"joinMeeting, joinMeetingResult=%d", joinMeetingResult);
    }
  } @catch (NSError *ex) {
      reject(@"ERR_UNEXPECTED_EXCEPTION", @"Executing joinMeeting", ex);
  }
}

**Android**:

> @ReactMethod
  public void joinMeetingWithPassword(
    final String displayName,
    final String meetingNo,
    final String password,
    Promise promise
  ) {
    try {
      meetingPromise = promise;
      ZoomSDK zoomSDK = ZoomSDK.getInstance();
      if(!zoomSDK.isInitialized()) {
        promise.reject("ERR_ZOOM_JOIN", "ZoomSDK has not been initialized successfully");
        return;
      }
      final MeetingService meetingService = zoomSDK.getMeetingService();
      JoinMeetingOptions opts = new JoinMeetingOptions();
      JoinMeetingParams params = new JoinMeetingParams();
      params.displayName = displayName;
      params.meetingNo = meetingNo;
      params.password = password;
      int joinMeetingResult = meetingService.joinMeetingWithParams(reactContext.getCurrentActivity(), params, opts);
      Log.i(TAG, "joinMeeting, joinMeetingResult=" + joinMeetingResult);
      if (joinMeetingResult != MeetingError.MEETING_ERROR_SUCCESS) {
        promise.reject("ERR_ZOOM_JOIN", "joinMeeting, errorCode=" + joinMeetingResult);
      }
    } catch (Exception ex) {
      promise.reject("ERR_UNEXPECTED_EXCEPTION", ex);
    }
  }

Also, I found that when I did the pod install, it gave me an error of missing homepage in podspec file here in the code:

> s.homepage     = ""

I overcame this error with placing your homepage url there as follows:

> s.homepage     = "https://github.com/mieszko4/react-native-zoom-us"

I have checked that "joinMeetingWithPassword" methods on iOS simulator iPhone 11 and Android physical device One Plus 7T works well, so I request you to go ahead and update the changes in the package with iOS and android methods and the podspec file.

**Comment by KawaljeetSBagga** [comment]
Please LMK if I should do a PR.

**Comment by mieszko4** [comment]
thnx @KawaljeetSBagga. Sure if you can do a pr that would be great

**Comment by KawaljeetSBagga** [comment]
@mieszko4 We are good to merge

**Comment by KawaljeetSBagga** [comment]
@mieszko4 Hey please LMK once done, so that we can go ahead and close this issue. Thanks!

**Comment by KawaljeetSBagga** [comment]
@mieszko4  It also seems that inside ios folder RNZoomUS.podspec file still has s.homepage as blank string, it has not been updated on npm server, its just updated on github. Please update it.

**Comment by mieszko4** [comment]
Thnx @KawaljeetSBagga, it is merged. I will publish the npm once I resolve quota issues with git-lfs

**Comment by KawaljeetSBagga** [comment]
@mieszko4 Thank you so much. Please also LMK once npm is updated.

**Comment by KawaljeetSBagga** [comment]
@mieszko4 Hey when can we expect a npm publish?

**Comment by KawaljeetSBagga** [comment]
Hey @mieszko4. The app builds are works properly, but when I archive it from xcode, I get many errors that point inside the library. Here's the screenshot for the same: 
![Screenshot 2020-05-12 at 8 35 20 PM](https://user-images.githubusercontent.com/60910844/81710240-3b574d00-9490-11ea-801c-c77ade4d2d6d.png)

**Comment by mieszko4** [comment]
I've finally unlock the publishing of this npm. I will need to see the issue you are facing with build, though

**Comment by amdrade** [comment]
@mieszko4 thanks for react-native-zoom-us!
What version of the zoom.us SDK?

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
