### ISSUE TITLE
JoinMeeting fails to show the zoom UI (sometimes)

### ISSUE THREAD

**Issue by Md-Mudassir47** [mieszko4/react-native-zoom-us#162]
@mieszko4  I've attached a video showing the demonstration of the issue & the issue is that when initially the app opens and user tries to join the meeting it works fine, & when I reload the app and then try to join again it doesn't show the UI, though the status is visible on the console log as connecting. Later I close the app and re-open it and try to join then it works.

I thought i might be an emulator issue. but on real devices it actually happens on the initial app launch itself (sometimes), then the user has to close the app and re-open it, in order for it to work.

[Video Demonstration](https://drive.google.com/file/d/1WtpbKNfmpA039XQGdeCd7LlnKh0AmuOQ/view?usp=sharing)

The issue occurs on both the platforms & quite frequently on iOS.

Version Used: `react-native-zoom-us": "^6.6.0,`

**Comment by Md-Mudassir47** [comment]
> Thnx for sharing. It happens to me, too. My guess is that the issue is with 2nd initialization of the sdk native lib. Not sure what the reason is... (one guess is that it gets reattached to an another or outdated native "view component")

As per my analysis here's what i found
**Scenario 1**: Initial load, `joinMeeting` works fine and when I leave the meeting it takes me back to the previous screen from where i joined.
**Scenario 2:** Initial Load then Refresh, After joining a meeting i refresh the app from terminal ( keeping the zoom meeting ui opened) and then i leave the meeting & it doesn't take me back to the previous screen from where i joined, instead it exits the app completely. It's like the view got detached from the app when i refreshed it.

**Comment by saurabhkanswal** [comment]
@mieszko4 any solution to this problem, I am also facing this issue.
Although the user is joined to the meeting, only the meeting UI didn't show up.
