### ISSUE TITLE
ZoomEmitter is not receiving events.

### ISSUE THREAD

**Issue by nitingraphy** [mieszko4/react-native-zoom-us#166]
When I join any meeting for the first time, The SDK gets initialized, the user joins a meeting, and ZoomEmitter gets all the related events perfectly. But when I leave that meeting and join it again, It's not receiving any event.

For the second time when I join the meeting, ZoomEmitter gets detached and unable to get any event. I guess there is some error in this SDK.

**Comment by zvs001** [comment]
I think I had similar issue.
When I work with android in dev, sometimes I don't receive events at all. Even after app close and relaunch.
Not sure what reason for it.

I had scenario that events were working after `run-android`, but stopped working after reload and all subsequent reloads/app relaunches.
