### ISSUE TITLE
Unexpected identifier '_reactNativeZoomUs'

### ISSUE THREAD

**Issue by EdgarXongas** [mieszko4/react-native-zoom-us#167]
Unexpected identifier '_reactNativeZoomUs'. 
Expected ';' after variable declaration

no stack
no stack

**Comment by mieszko4** [comment]
That looks like a syntax error from your code - try to start with demo app - https://github.com/mieszko4/react-native-zoom-us-test

**Comment by EdgarXongas** [comment]
@mieszko4 i've tried with on ejected expo app it worked perfectly
I apreciate your work =)

**Comment by muhamadjawad** [comment]
Any solution to this?.
Please i need help

**Comment by mieszko4** [comment]
@muhamadjawad Please open another issue and provide more details and you will get a higher chance for someone helping you :)
