### ISSUE TITLE
class file for us.zoom.androidlib.util.IListener not found in version 5.10.0

### ISSUE THREAD

**Issue by ritesh2204** [mieszko4/react-native-zoom-us#168]
Its was running perfect but 5 days later when I rebuild my project then its throw error in package says
class file for us.zoom.androidlib.util.IListener not found.

version:    "react-native-zoom-us": "^5.10.0",

Error: 

> Task :react-native-zoom-us:compileDebugJavaWithJavac FAILED
RNZoomUsModule.java:44: error: cannot access IListener
public class RNZoomUsModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, InMeetingServiceListener, MeetingServiceListener, InMeetingShareController.InMeetingShareListener, LifecycleEventListener {
       ^
  class file for us.zoom.androidlib.util.IListener not found

FAILURE: Build failed with an exception.

Any Solution.

**Comment by mieszko4** [comment]
Any reason why you are not using the newest version (currently `6.6.1`) ?

**Comment by mieszko4** [comment]
Try with newest `6.9.0`
