### ISSUE TITLE
Android back button handling

### ISSUE THREAD

**Issue by sridhard** [mieszko4/react-native-zoom-us#169]
Hi,

In android when back button is pressed(Hardware back), the app is getting closed. instead I want to leave the meeting and goback to previous screen. Can you pls help me to implement this behaviour

To implement this we need to override onBackPressed(). There is a way to override back handler in zoom. It is explained in link https://devforum.zoom.us/t/onbackpress-to-go-out-of-application/9297/3. To override back handler as per zoom article we need a activity. But in react-native-zoom-us i did not find activity.

Can you please let me know about the implementation method? I cam implement and give PR if changes are required in react-native-zoom-us

Thanks

**Comment by mieszko4** [comment]
:thinking: Since this is a react-native have you tried with adding `BackHandler` as mentioned in https://reactnative.dev/docs/backhandler ?

**Comment by sridhard** [comment]
@mieszko4 I tried all possible ways and it is not working with BackHandler. 

As per zoom docs we need to override the backhandler in the android activity. Can you help me how to do as per zoom docs. https://devforum.zoom.us/t/onbackpress-to-go-out-of-application/9297/3.

**Comment by mieszko4** [comment]
@sridhard You are right, a custom meeting activity had to be added. In 6.6.1 I've added a custom activity with back button causing leave meeting dialog.
You can see how to attach it in https://github.com/mieszko4/react-native-zoom-us-test/pull/34
