### ISSUE TITLE
Build working on Android, but on ios its giving an error TypeError: null is not an object (evaluating '_reactNativeZoomUs.default.initialize')

### ISSUE THREAD

**Issue by pkpardeep482** [mieszko4/react-native-zoom-us#17]
"react": "16.11.0",
    "react-native": "0.62.2",
 "react-native-zoom-us": "^2.0.0",

**Comment by pkpardeep482** [comment]
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>

found this in IOs

**Comment by KawaljeetSBagga** [comment]
Try this : [https://github.com/joltup/rn-fetch-blob/issues/461#issuecomment-553355501](url)

**Comment by amdrade** [comment]
> ../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
> #import <React/RCTDefines.h>
> 
> found this in IOs

I solved it like this [https://github.com/mieszko4/react-native-zoom-us/issues/10#issuecomment-636580013](https://github.com/mieszko4/react-native-zoom-us/issues/10#issuecomment-636580013)

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
