### ISSUE TITLE
[iOS] build Failed with ZoomSDK on real device.

### ISSUE THREAD

**Issue by pankajdreamsoft** [mieszko4/react-native-zoom-us#174]
I am using below versions:

"react-native": "0.64.2",
 "react": "17.0.1",
 "react-native-zoom-us": "^6.6.1",

When I build for iOS in real device i got an error as below as well as build failed for simulator.

![ZoomSDK_issue_iosbuild](https://user-images.githubusercontent.com/84914034/147227149-ce798f83-90c1-4c13-b762-7fdff02649f0.png)

Error message :

PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Library/Developer/Xcode/DerivedData/ihealth-bpfblxlkpwisgleeobrhoiecggom/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ZoomSDK.build/Script-C0538A32EF325BA425A38332AD28B13B.sh (in target 'ZoomSDK' from project 'Pods')
    cd /ios/Pods
    /bin/sh -c /Library/Developer/Xcode/DerivedData/ihealth-bpfblxlkpwisgleeobrhoiecggom/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/ZoomSDK.build/Script-C0538A32EF325BA425A38332AD28B13B.sh
    
    Selected xcframework slice ios-arm64_armv7
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" "/ios/Pods/ZoomSDK/zoom-sdk-ios-5.7.1.645/lib/MobileRTC.xcframework/ios-arm64_armv7/*" "/Library/Developer/Xcode/DerivedData/ihealth-bpfblxlkpwisgleeobrhoiecggom/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/ZoomSDK"
building file list ... done
MobileRTC.framework/
MobileRTC.framework/Info.plist
MobileRTC.framework/MobileRTC
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/rsync.c(244) [sender=2.6.9]

**Comment by mieszko4** [comment]
Perhaps you have some specific settings in xcode projects. Please try to clone and build https://github.com/mieszko4/react-native-zoom-us-test. You should find there what settings are needed for ZoomUs SDK to work.

**Comment by mieszko4** [comment]
Now https://github.com/mieszko4/react-native-zoom-us-test/ is with newest version of the lib 6.7.0.
