### ISSUE TITLE
Zoom video doesn't rotate when screen is rotated to Landscape (on iOS)

### ISSUE THREAD

**Issue by Niranjankr0** [mieszko4/react-native-zoom-us#176]
its has been fixed on previous 6.1.4 . Some days earlier I have updated with 6.6.1  and same issue happen again.

**Comment by saurabh-mh** [comment]
We have also seen rotation issue after upgrading to latest version. Can we please look into it as this was resolved earlier.

**Comment by mieszko4** [comment]
Perhaps you could try with 6.7.0

**Comment by mieszko4** [comment]
There is a newer issue https://github.com/mieszko4/react-native-zoom-us/issues/204
