### ISSUE TITLE
Note: D:\react-native\jitsi\newZoom\android\app\src\debug\java\com\newzoom\ReactNativeFlipper.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by riyas145** [mieszko4/react-native-zoom-us#178]
Note: D:\react-native\jitsi\newZoom\android\app\src\debug\java\com\newzoom\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
 
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-zoom-us": "^6.6.1"

**Comment by mieszko4** [comment]
Is that a fatal error or just a warning?

**Comment by riyas145** [comment]
fatal error i'm not able to move further

**Comment by mieszko4** [comment]
It is hard yo say from what you've sent. Does running demo (https://github.com/mieszko4/react-native-zoom-us-test) work for you?

**Comment by mieszko4** [comment]
Try `6.9.0`
