### ISSUE TITLE
startMeeting for login user

### ISSUE THREAD

**Issue by Ghoral** [mieszko4/react-native-zoom-us#179]
Hello,
Can you add start meeting for login user. that would be great thankyou.

**Comment by mieszko4** [comment]
Not sure what you mean exactly but you can see example of start meeting here: https://github.com/mieszko4/react-native-zoom-us-test/

**Comment by mieszko4** [comment]
Feel free to reopen.

**Comment by Ghoral** [comment]
Sure thankyou..the problem has been solved for now.
