### ISSUE TITLE
APp Crashing in android 12

### ISSUE THREAD

**Issue by Niranjankr0** [mieszko4/react-native-zoom-us#180]
Fatal Exception: java.lang.SecurityException
Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@62a94c92: HeadsetService
keyboard_arrow_up
android.os.Parcel.createExceptionOrNull (Parcel.java:2439)
arrow_drop_down
android.bluetooth.BluetoothHeadset.getConnectedDevices (BluetoothHeadset.java:601)
arrow_right
us.zoom.androidlib.util.HeadsetUtil$1.onServiceConnected (HeadsetUtil.java:108)
android.bluetooth.BluetoothHeadset$3.handleMessage (BluetoothHeadset.java:1491)
arrow_drop_down
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1065)

**Comment by ehabqadah** [comment]
We are facing the same issue with Android 12, even after manually asking to grant BLUETOOTH_CONNECT & READ_PHONE_STATE permissions. We are stil geting the 
```
java.lang.RuntimeException: Unable to create service com.zipow.videobox.share.ScreenShareServiceForSDK: java.lang.IllegalArgumentException: package name: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
```

**Comment by qusaisafa** [comment]
Same issue here with android 12, any solution?

**Comment by pmogollons** [comment]
This is problably caused by the version of the SDK that this package uses. I think we are 3 or 4 versions behind.

**Comment by pmogollons** [comment]
Actually zoom sdk is not compatible with android 12 yet, so nothing to do even if we update to latest SDK until they support it.

**Comment by pmogollons** [comment]
Fixed in latest version, please report back if you get any issues after updating.

@mieszko4 can you close this issue please.
