### ISSUE TITLE
Failed to transform mobilertc-5.7.1.1268.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.7.1.1268) to mat

### ISSUE THREAD

**Issue by kundanray1** [mieszko4/react-native-zoom-us#182]
Failed to transform mobilertc-5.7.1.1268.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.7.1.1268) to match attributes {artifactType=android-aar-metadata, org.gradle.status=release}.

please help.

**Comment by pmogollons** [comment]
Havent seen this exact issue before, but might be fixed with the new version with updated sdk coming soon.

**Comment by kundanray1** [comment]
Sure bro

**Comment by mieszko4** [comment]
Please try with 6.7.0
