### ISSUE TITLE
Waiting Room Header text is transparent In IOS only

### ISSUE THREAD

**Issue by sumeetHalder** [mieszko4/react-native-zoom-us#183]
@mieszko4 After join the meeting , In Waiting Room header text is getting Overlap with other screen text, looks like some part of waiting room page header title is transparent.  
Have uploaded the image file.., please have a look into it

What can be done to resolve this bug?.. (I have checked with Zoom App., its working fine there!!)

![image](https://user-images.githubusercontent.com/85999457/150346320-91d5fa3f-edb7-4bec-8ae5-ed6ab8b3a6f5.png)

**Comment by mieszko4** [comment]
Perhaps you could try with new version v6.7.0

**Comment by pmogollons** [comment]
This was an issue on the SDK itself, is now fixed in latest version as shown in the changelog.

https://marketplace.zoom.us/docs/guides/stay-up-to-date/changelog/

> Issue where the navigation bar in the default waiting room UI was transparent.

@mieszko4 can you please close this issue.
