### ISSUE TITLE
[android] how to hide meeting info

### ISSUE THREAD

**Issue by Devillord18** [mieszko4/react-native-zoom-us#185]
I am a beginner and had tried several things to hide meeting info from the students so that they could not share the meeting info to other students

**Comment by mieszko4** [comment]
Have you tried `noButtonShare` option  of `joinMeeting`?

**Comment by Devillord18** [comment]
Sir, I have got the solution of my problem after some research.
Thank you for your response

**Comment by mieszko4** [comment]
Great @Devillord18 , I will close this ticket then. But would be great if you posted your solution for others to see in the future.

**Comment by Devillord18** [comment]
Sure Sir
