### ISSUE TITLE
5.9.1.x Upgrade Help

### ISSUE THREAD

**Issue by zvs001** [mieszko4/react-native-zoom-us#186]
There are updated sdks that can be integrated.
If someone can help with integration, it would be great.

| OS| version | issue |
| :--: | :--: | :--: |
| IOS |  5.9.1.2191 | https://github.com/zoom-us-community/zoom-sdk-pods/issues/6 |
| Android | 5.9.1.3674 |  https://github.com/zoom-us-community/jitpack-zoom-us/issues/5 |

**Comment by pmogollons** [comment]
Almost ready, tomorrow ill be testing the changes and making a PR.
