### ISSUE TITLE
After adding MobileRTC.framework to Libraries XCODE, Only headers are getting copied, no any other file getting copied. Please check screenshot 

### ISSUE THREAD

**Issue by pkpardeep482** [mieszko4/react-native-zoom-us#19]
But in actual, MobileRTC.framework contains info.plist, MobileRTC, Modules.  Please help me out

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
