### ISSUE TITLE
Launching app from launcher icon after going to Home launches React Native Activity 

### ISSUE THREAD

**Issue by neeraj-nh** [mieszko4/react-native-zoom-us#192]
I have only one Activity in my application - MainActivity. This activity has android:launchMode=“singleTask” in it’s tag in AndroidManifest. This is a requirement from expo for deep linking : https://github.com/expo/fyi/blob/main/setup-android-uri-scheme.md.

I launch zoom by calling joinMeeting, which as far as I can tell, starts it’s own activity internally.

When the user goes back to home screen by pressing the Home button, and relaunches my app using the app launcher icon - MainActivity is brought to the front. The Zoom meeting is still going on. I can hear the audio. I can see the notification in the tray. But there is no way for me to navigate to the Zoom Activity from my app. User can navigate through the notification, but I want to navigate them to the right place in my app.

Is this something other users of the library are facing ? How are you handling it ? 

Also posted here: https://devforum.zoom.us/t/is-there-a-way-to-bring-existing-instance-of-zooms-activity-to-the-front/63969 .

**Comment by nkpatnis** [comment]
```
  @ReactMethod
  public void startMeeting(
    final ReadableMap paramMap,
    Promise promise
  ) {
    meetingPromise = promise;

    UiThreadUtil.runOnUiThread(new Runnable() {
      @Override
      public void run() {
        try {
          ZoomSDK zoomSDK = ZoomSDK.getInstance();
          if(!zoomSDK.isInitialized()) {
            meetingPromise.reject("ERR_ZOOM_START", "ZoomSDK has not been initialized successfully");
            return;
          }

          final String meetingNo = paramMap.getString("meetingNumber");
          final MeetingService meetingService = zoomSDK.getMeetingService();
          if(meetingService.getMeetingStatus() != MeetingStatus.MEETING_STATUS_IDLE) {
            long lMeetingNo = 0;
            try {
              lMeetingNo = Long.parseLong(meetingNo);
            } catch (NumberFormatException e) {
              meetingPromise.reject("ERR_ZOOM_START", "Invalid meeting number: " + meetingNo);
              return;
            }

            if(meetingService.getCurrentRtcMeetingNumber() == lMeetingNo) {
              meetingService.returnToMeeting(reactContext.getCurrentActivity());
              meetingPromise.resolve("Already joined zoom meeting");
              return;
            }
          }

          StartMeetingOptions opts = new StartMeetingOptions();
          MeetingViewsOptions view = new MeetingViewsOptions();
```
by looking this code it seems if you again call joinMeeting it should rejoin the same ongoing meeting, I am also facing same issue, will implement this and update here for others.
