### ISSUE TITLE
Inconsistent promise resolve

### ISSUE THREAD

**Issue by gladiatorgiftson** [mieszko4/react-native-zoom-us#193]
while joining a meeting the promise is not resolved as expected not throwing any error but meeting is joined subsequent lines also not executing 

```
 const joinAMeeting = async (meetingNumber, password) => {
     await ZoomUs.joinMeeting({
      userName: userName,
      meetingNumber: meetingNumber,
      password: password,
      autoConnectAudio: true,
    })
     console.log("Meeting joined")  <- This line is not executing 
  };
```

i tried with ` then` that's when I found the promise is not resolving if resolved it gives `Connected to zoom meeting` 
i wanted to know if there's a way to find the meeting is ended

**Comment by mieszko4** [comment]
:thinking: I am not sure why `console.log` does not execute for you.
But you should be able to check if meeting is started/ended with events, i.e. with `ZoomEmitter`.
Check https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L171-L187 for an example.

**Comment by gladiatorgiftson** [comment]
Thank you @mieszko4
