### ISSUE TITLE
```usesCleartextTraffic``` false by default causing issue

### ISSUE THREAD

**Issue by Jothinayagan** [mieszko4/react-native-zoom-us#195]
Environment: 
"react": "17.0.1"
"react-native": "0.64.2"
"react-native-zoom-us":"^6.6.1"

```javascript
Error: 
Attribute application@usesCleartextTraffic value=(true) from AndroidManifest.xml:8:9-44
    is also present at [com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.9.1.3674] AndroidManifest.xml:85:9-45 value=(false).
    Suggestion: add 'tools:replace="android:usesCleartextTraffic"' to <application> element at AndroidManifest.xml:7:5-12:19 to override.
```

As per Android Developers documentation, it is not good practice to disable the ```usesCleartextTraffic```

https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic

**Comment by mieszko4** [comment]
This is requirement of Zoom Us SDK as of v5.9.0 (https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/android-meeting-sdk-v5-9-0) so we cannot avoid this until they fix it.
See our README.md for the steps of what exceptions need to be provided (https://github.com/mieszko4/react-native-zoom-us#android)

**Comment by Jothinayagan** [comment]
> This is requirement of Zoom Us SDK as of v5.9.0 (https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/android-meeting-sdk-v5-9-0) so we cannot avoid this until they fix it. See our README.md for the steps of what exceptions need to be provided (https://github.com/mieszko4/react-native-zoom-us#android)

README.md steps works. Thanks, @mieszko4
