### ISSUE TITLE
Saving the secret on the client side?

### ISSUE THREAD

**Issue by shaharsol** [mieszko4/react-native-zoom-us#2]
in your basic example you initialize the object with key, secret, and domain. Isn't secret and signing should be done on some server and then transmit generated token to the mobile app?

**Comment by mieszko4** [comment]
I do not think zoom sdk provides a token based authentication. based on their android sdk it is passing od key/secret/domain https://marketplace.zoom.us/docs/sdk/native-sdks/android/build-your-first-zoom-app/join-meeting

**Comment by mieszko4** [comment]
I mean, they mention some generating of signature on the server (https://gist.github.com/joshuawoodward/7574df3df9a089e2663582a2cf9f188b) but I did not find any example of how to use this signature.

**Comment by mieszko4** [comment]
This is an old issue, I will close it for now. Feel free to reopen.
