### ISSUE TITLE
Upgrade Exoplayer

### ISSUE THREAD

**Issue by sridhard** [mieszko4/react-native-zoom-us#200]
Hi,

Current exoplayer version used by zoom sdk is ols. Exoplayer version 2.17.x have solved many issues. We want to use latest version of exoplayer for the DASH-DRM playback. But we are not able to upgrade exoplayer because zoom sdk is using old version.

Can you please let me know how can we upgrade exoplayer to 2.17. If this requires changes in zoom sdk then what is the plan for the same.

thanks

**Comment by mieszko4** [comment]
I see that the newest Android Zoom SDK (v5.10.1) updates exoplayer to 2.16.1 (https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-10-1?embed=true)
I guess we could update Android Zoom SDK in the lib and try if it will work correctly with exoplayer to 2.17.x.

Meanwhile, you can try to disable exoplayer from the lib by following this guide: https://github.com/mieszko4/react-native-zoom-us/blob/master/docs/TROUBLESHOOTING.md and add exoplayer 2.17.x directly in your project and see if there are any issues.

**Comment by mieszko4** [comment]
I added issue to update Android Zoom SDK - https://github.com/mieszko4/react-native-zoom-us/issues/201

**Comment by mieszko4** [comment]
Done in `6.9.0`
