### ISSUE TITLE
Upgrade android Zoom SDK to v5.10.1

### ISSUE THREAD

**Issue by mieszko4** [mieszko4/react-native-zoom-us#201]

**Comment by ehabqadah** [comment]
@mieszko4 we would appreciate it if you can push it as the old zoom SDK version has some issues on Andriod 12, please refer to the https://devforum.zoom.us/t/exception-only-for-samsung-devices/66589/9

**Comment by AmnehSalameh** [comment]
> @mieszko4 we would appreciate it if you could push it as the old zoom SDK version has some issues on Andriod 12, please refer to the https://devforum.zoom.us/t/exception-only-for-samsung-devices/66589/9
I am facing the same issue 
@mieszko4 Is this happening anytime soon? Thanks

**Comment by qusaisafa** [comment]
> @mieszko4 we would appreciate it if you can push it as the old zoom SDK version has some issues on Andriod 12, please refer to the https://devforum.zoom.us/t/exception-only-for-samsung-devices/66589/9

@mieszko4 could you please help
