### ISSUE TITLE
Transform artifact mobilertc.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.9.6.4777) with DexingWithClasspathTransform

### ISSUE THREAD

**Issue by aditiproctur** [mieszko4/react-native-zoom-us#202]
### Platform
```
 Android 
 buildToolsVersion = "30.0.2"
 minSdkVersion = 21
 compileSdkVersion = 30
 targetSdkVersion = 30
```

### Issue
```
Transform artifact mobilertc.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.9.6.4777) with DexingWithClasspathTransform

> Task :app:mergeExtDexDebug FAILED
ReactNativeFirebase WARNING: NPM package '@react-native-firebase/crashlytics' depends on '@react-native-firebase/app' v9.0.0 but found v8.4.7, this might cause build issues or runtime crashes.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
846 actionable tasks: 8 executed, 838 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
AGPBI: {"kind":"error","text":"Default method desugaring of `com.zipow.videobox.fragment.t2` failed because its super class `us.zoom.androidlib.app.ZMDialogFragment` is missing","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'mobilertc.aar (com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.9.6.4777)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/procturdev/.gradle/caches/transforms-2/files-2.1/17534fec069a54d995632f21b31b3d6c/mobilertc-5.9.6.4777-runtime.jar.
         > Error while dexing.
```

Facing above mention error on android.

**Comment by mieszko4** [comment]
Which version of the lib you are using? Does example app work for you (https://github.com/mieszko4/react-native-zoom-us-test)?

I see you are using firebase so perhaps that's related.

**Comment by praveens96** [comment]
similar error I am getting

`Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.airbnb.android:lottie:4.0.0.
     Required by:
         project :app > project :react-native-zoom-us
      > Could not resolve com.airbnb.android:lottie:4.0.0.
         > Could not get resource 'https://www.jitpack.io/com/airbnb/android/lottie/4.0.0/lottie-4.0.0.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/airbnb/android/lottie/4.0.0/lottie-4.0.0.pom'.
               > Read timed out
   > Could not resolve com.github.zoom-us-community.jitpack-zoom-us:commonlib:5.9.6.4777.
     Required by:
         project :app > project :react-native-zoom-us > com.github.zoom-us-community:jitpack-zoom-us:5.9.6.4777
      > Skipped due to earlier error
   > Could not resolve com.github.zoom-us-community.jitpack-zoom-us:mobilertc:5.9.6.4777.
     Required by:
         project :app > project :react-native-zoom-us > com.github.zoom-us-community:jitpack-zoom-us:5.9.6.4777
      > Skipped due to earlier error`

**Comment by mieszko4** [comment]
Please try with `6.9.0`
