### ISSUE TITLE
EXC_BAD_ACCESS  UIAlertController iOS lib -> v6.9.0

### ISSUE THREAD

**Issue by nkpatnis** [mieszko4/react-native-zoom-us#209]
EXC_BAD_ACCESS: delegate > onSinkMeetingMyAudioTypeChange > respondsToSelector: >
Attempted to dereference garbage pointer 0xfe4dc0ef0.

**Comment by mieszko4** [comment]
That's most likely related to Zoom SDK. I hope updating SDK to new version will help (https://github.com/mieszko4/react-native-zoom-us/issues/206)

**Comment by mieszko4** [comment]
Closing due because of release of `6.11.0`. Feel free to re-open with more details if it happens to you on `6.11.0`
