### ISSUE TITLE
Zoom SDK version is too low

### ISSUE THREAD

**Issue by prakarti** [mieszko4/react-native-zoom-us#21]
After implementing zoom us code , on start meeting getting error Zoom SDK version is too low,
According zoom - any Client SDK versions below 4.6.21666.0429 will no longer be operational from June 01.

**Comment by roket123** [comment]
I found the same issue error 4 Zoom SDK version is too low if any solution Please

**Comment by mieszko4** [comment]
I need to update zoom sdk for this lib.
Unfortunately zoom sdk is not supported for newest xcode yet so that complicates things a bit for me.

**Comment by roket123** [comment]
> I need to update zoom sdk for this lib.
> Unfortunately zoom sdk is not supported for newest xcode yet so that complicates things a bit for me.

Thanks and Android also
If you recommend to tray any thing for android tell me to try

**Comment by calqlum123** [comment]
Hello, please could you confirm if this is has been updated?

**Comment by Yatanvesh** [comment]
https://github.com/mieszko4/react-native-zoom-us/pull/25
Please try this PR, for android. I've updated the sdk version and config.

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
