### ISSUE TITLE
[Android] App crashing when playing video

### ISSUE THREAD

**Issue by Ben8823** [mieszko4/react-native-zoom-us#210]
Hello,

I'm using `react-native-video@5.2.0` in my application. If I also use `react-native-zoom-us` I'm getting crashes if I try to play videos with this exception
```   
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/video/VideoListener;
 at com.brentvatne.exoplayer.ReactExoplayerView.createViews(ReactExoplayerView.java:226)
```
I've seen the troubleshoot document and understood that there are conflicts between different exo player versions. So, I downgraded `react-native-zoom-us` to 6.8.1 which uses the same exo player version as react-native-video (2.13.3). But my application still crashes when  try to play videos.

Do you have any suggestions to work around this?

**Comment by mieszko4** [comment]
Hey @Ben8823. I see you closed this issue. Would be great to provide some info of how you resolved it :)

**Comment by Ben8823** [comment]
Hey @mieszko4 . Never mind, the downgrade to 6.8.1 did the trick. Some node modules did not update as expected.
