### ISSUE TITLE
ibrary not found for -lstdc++.6.0.9

### ISSUE THREAD

**Issue by rakeshkumar217** [mieszko4/react-native-zoom-us#22]
i am using below versions:

    "react": "16.11.0",
    "react-native": "0.62.2",
 "react-native-zoom-us": "^2.0.2",

xcode: 11.3.1

Missing steps: 

1. unable to add libstdc++.6.0.9.tbd 
2. unable to add this line: $(SRCROOT)/../node_modules/react-native-zoom-us/ios/libs

I am struggling for 3 days. 

Any solution.
THANKS.

**Comment by amdrade** [comment]
Update version resolve work for me
1- [dyld: Library not loaded: /usr/lib/libstdc++.6.dylib](https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/get-help/faq#1-dyld-library-not-loaded-usrliblibstdc6dylib)

**Comment by Palwisha77** [comment]
facing the same issue @amdrade  can u please tell me that how can I update the version in my react native project.

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
