### ISSUE TITLE
Cannot constrain type: @NotNull

### ISSUE THREAD

**Issue by andrew-schenk** [mieszko4/react-native-zoom-us#220]
App fails to build for Android when including `react-native-zoom-us` v6.13.0.

M1 Mac
React Native: 0.68.2
Kotlin: 1.6.0
Gradle: 7.3.3
AGP: 7.0.4

```
Caused by: com.android.tools.r8.utils.w$c: com.android.tools.r8.internal.b: Cannot constrain type: @NotNull com.zipow.cmmlib.AppContext$AppContextImpl {} for value: v0 by constraint: LONG
```

Also affects all versions of `react-native-zoom-us` going back to and including 6.7.0

Android built with `react-native-zoom-us` v6.6.1

**Comment by mieszko4** [comment]
Thnx, I am planning to upgrade RN (https://github.com/mieszko4/react-native-zoom-us-test/issues/47) so that may give more insight on this issue.

Perhaps it is related to gradle - I see you are using 7.3.3 but ZoomUs SDK upgraded to 7 in 5.11 (https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-0). Also, in 5.11 the removed `com.android.tools:r8:3.0.73` so maybe upgrading to 5.11 will fix it. I have an opened PR (https://github.com/mieszko4/react-native-zoom-us/pull/219) but it fails to build for me on real device so I need to figure out why before I can merge it to this lib (at the moment I am out of ideas :))

**Comment by andrew-schenk** [comment]
Thanks, I'll give it a go with

`react-native-zoom-us: 6.13.0`
and patching it to use the 5.11 ZoomUS SDK and see if that results in a different error or success.
```
implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.11.0.6883'
```

**Comment by andrew-schenk** [comment]
I tried this morning with the changes from https://github.com/mieszko4/react-native-zoom-us/pull/219 but am still getting the same error as before.

I've also tried forcing R8 to a newer version

```
        maven {
            url = uri("https://storage.googleapis.com/r8-releases/raw")
        }

    }
    dependencies {
        classpath 'com.android.tools:r8:3.2.55'
```

Something else that sticks out to me is Proguard.  The project I am working on has quite a lot of extra zoom proguard rules that aren't in the ReadMe here.

Finally, it may be worth trying to upgrade from React Native 68.2 -> 69.x.  The 0.69 version of React Native bumps AGP from 7.0.4 -> 7.1.1.  🤷

**Comment by andrew-schenk** [comment]
Upgrading to React Native 69.1 got past the original error
```
Caused by: com.android.tools.r8.utils.w$c: com.android.tools.r8.internal.b: Cannot constrain type: @NotNull com.zipow.cmmlib.AppContext$AppContextImpl {} for value: v0 by constraint: LONG
```
The app now builds with 
```
implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.11.0.6883'
```

I have to do more testing to see if all the Zoom functionality works as expected.

**Comment by mieszko4** [comment]
@andrew-schenk Does join/start meeting works for you?

It builds but still crashes for me with React Native 69.1.

It looks like the problem is that Zoom SDK embeds `**/libc++_shared.so` and when we do `pickFirst` it is incompatible and crashes on join/start meeting.
Seems like a similar issue to https://github.com/realm/realm-kotlin/issues/694. In `realm-kotlin` (3rd party lib) they removed `/libc++_shared` (https://github.com/realm/realm-kotlin/pull/620/files).

**Comment by andrew-schenk** [comment]
@mieszko4 Trying to join a meeting will crash the app with something like this

```
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address"
```

That looks like the same error as the realm-kotlin that you linked.  How would we go about patching that here?

**Comment by andrew-schenk** [comment]
@mieszko4 where is the `mobilertc.aar` file located?  I cannot find it.

**Comment by andrew-schenk** [comment]
I tried upgrading to the latest Android Meeting Zoom SDK, version `5.11.1.6928` and ran into this compile issue.

```
AGPBI: {"kind":"error","text":"Cannot constrain type: @NotNull com.zipow.cmmlib.AppContext$AppContextImpl {} for value: v0 by constraint: LONG","sources":[{"file":"/Users/andrew.schenk/.gradle/caches/transforms-3/59b24b343e1aea85a7e421d6d8ecde31/transformed/jetified-mobilertc-5.11.1.6928-runtime.jar"}],"tool":"D8"}
```

https://github.com/andrew-schenk/jitpack-zoom-us

```
-    implementation 'com.github.zoom-us-community:jitpack-zoom-us:5.10.3.5614'
+    implementation 'com.github.andrew-schenk:jitpack-zoom-us:5.11.1.6928'
```

It seems that I've come full circle.  😢

**Comment by andrew-schenk** [comment]
A little more information.  It seems like `mobilertc` contains both Jetified and non-jetified code.

```
WARNING: [Processor] Library '/Users/andrew.schenk/.gradle/caches/modules-2/files-2.1/com.github.zoom-us-community.jitpack-zoom-us/mobilertc/5.10.3.5614/4663dde1b582b298c463bab8ce73a60907a1248f/mobilertc-5.10.3.5614.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Callback'
```

This was using `5.10.3.5614`

**Comment by mieszko4** [comment]
> @mieszko4 where is the `mobilertc.aar` file located? I cannot find it.

@andrew-schenk Sorry for this late reply. I guess you already figured out that we use jitpack. This file is located in another repository see https://github.com/zoom-us-community/jitpack-zoom-us/tree/master/libs.
