### ISSUE TITLE
[Android] React Native UI overlaps Zoom UI when user moves from background to foreground.

### ISSUE THREAD

**Issue by bhardwajMehul** [mieszko4/react-native-zoom-us#221]
In a particular case, when user is in meeting, the user goes into background and comes back to the app. The audio is coming i.e. the meeting still continues but the user observes the react-native UI not the Zoom UI which in ideal should be visible.

**Comment by mieszko4** [comment]
Which version do you user? It should be fixed in 6.13.0.

**Comment by bhardwajMehul** [comment]
Hey, @mieszko4 Got the issue resolved in the latest version. 
Thanks! mate. You've done a great work 😄
