### ISSUE TITLE
[iOS] Not able to see Meeting UI after Codepush

### ISSUE THREAD

**Issue by bshubham80** [mieszko4/react-native-zoom-us#222]
Greetings,

Version: "react-native-zoom-us@latest"

My concern is SDK UI not opening right after Codepush patch applied. I'm getting all the logs but not able to see the meeting UI.

Best regards

**Comment by zvs001** [comment]
First of all, let's make sure that you don't use `:latest` as a version.
It is first reason why it can stop working.

**Comment by bshubham80** [comment]
I have checked, I'm using "react-native-zoom-us@6.13.0" only.

**Comment by mieszko4** [comment]
Is it still an issue? Please try with newest `6.16.5`. Also, it may be tricky to deal with CodePush updates although I believe it may work because at some point I fixed a similar issue when reloading the app during development.
