### ISSUE TITLE
minimize option for android

### ISSUE THREAD

**Issue by ymakhfi** [mieszko4/react-native-zoom-us#223]
Are the new version of this lib include the minimize option for android?

**Comment by mieszko4** [comment]
There is no minimize option in this lib implemented.
However, could you explain more what you mean by `the minimize option`?

**Comment by ymakhfi** [comment]
I mean `Minimize Meeting` this option available on IOS , but not in android .

**Comment by mieszko4** [comment]
Explanation why it is not available on Android: https://devforum.zoom.us/t/android-doesnt-have-minimize-functinoality/9194
