### ISSUE TITLE
Host meeting 

### ISSUE THREAD

**Issue by BloodDSHOT** [mieszko4/react-native-zoom-us#225]
Hi Actually I want to host a meeting but didn't find any for Host meeting, so please can you let me know how to host a meeting

Thanks

**Comment by zvs001** [comment]
As I understand you need this: 
```
// Start Meeting
await ZoomUs.startMeeting({
  userName: 'Johny',
  meetingNumber: '12345678',
  userId: 'our-identifier',
  zoomAccessToken: zak,
  userType: 2, // optional
})
```

Host must provide zak token to start meeting.

**Comment by akanz** [comment]
Hey, I'm trying to host a meeting but I keep getting Error: 16, internalErrorCode=failed to start meeting with expired token. Any help will be appreciated!

**Comment by zvs001** [comment]
> Hey, I'm trying to host a meeting but I keep getting Error: 16, internalErrorCode=failed to start meeting with expired token. Any help will be appreciated!

Zak token works only for short period of time. I think ~2 hours.

**Comment by akanz** [comment]
Immediately I try to start a meeting, after a few seconds, I get the error.

**Comment by mieszko4** [comment]
I will close this. Feel free to reopen.
