### ISSUE TITLE
Screen Sharing Setup iOS

### ISSUE THREAD

**Issue by amdrade** [mieszko4/react-native-zoom-us#23]
how to setup screen share on iOS?

**Comment by mieszko4** [comment]
It looks like for iOS the procedure is complex to make it work.

Please check: https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/mastering-zoom-sdk/in-meeting-function/screen-share

I am not sure how much of these we could integrate int the plugin. You are welcome to create a pull request :)

**Comment by jcamins** [comment]
An approach to this was implemented in #58. Even with the updates we made to allow iOS screensharing without modifying the library, most of the work remains in your xcode project, as described in https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/mastering-zoom-sdk/in-meeting-function/screen-share

**Comment by mieszko4** [comment]
I will close this one, thnx @jcamins
