### ISSUE TITLE
Android App Crash After Package Install

### ISSUE THREAD

**Issue by muhammad-zain** [mieszko4/react-native-zoom-us#230]
- Facing a crash on Video Player after installing your package. I'm using [React Native Video](https://github.com/react-native-video/react-native-video) for playing videos.

Here is the detail of crash.

Didn't find class "com.google.android.exoplayer2.video.VideoListener" on path: DexPathList[[zip file "/data/app/~~KS8ya4w4BlF87-qJJvLSpw==/com.aimfit-KWGh_JOT6ox1LoJ7SKSYeQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~KS8ya4w4BlF87-qJJvLSpw==/com.aimfit-KWGh_JOT6ox1LoJ7SKSYeQ==/lib/arm64, /data/app/~~KS8ya4w4BlF87-qJJvLSpw==/com.aimfit-KWGh_JOT6ox1LoJ7SKSYeQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]

Working Fine for iOS.

**Comment by zvs001** [comment]
react-native-video didn't prepare update yet. I can suggest to install react-native-video directly from github.

I use npm version for IOS (5.2.1) and github version for Android. (6+)

**Comment by priyamego123** [comment]
Hey, my android app also gets crash after adding react-native-video, using latest version     "react-native-video": "^5.2.1",

**Comment by mieszko4** [comment]
Please try with newest 6.16.5.

**Comment by mieszko4** [comment]
Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.
