### ISSUE TITLE
Deprecated inside Module.java

### ISSUE THREAD

**Issue by aldiwijayaiskandar** [mieszko4/react-native-zoom-us#231]
Hi i was running issues with zoom so i decided to update the package but. i can't seem to run it

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081  
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:97: error: local variable intent is accessed from within inner class; needs to be declared final
              startZoomScreenShare(intent);
                                   ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:227: error: local variable promise is accessed from within inner class; needs to be declared final
            promise.reject("ERR_ZOOM_START", "ZoomSDK has not been initialized successfully");
            ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:238: error: local variable promise is accessed from within inner class; needs to be declared final
              promise.reject("ERR_ZOOM_START", "Invalid meeting number: " + meetingNo);
              ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:244: error: local variable promise is accessed from within inner class; needs to be declared final
              promise.resolve("Already joined zoom meeting");
              ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:273: error: local variable promise is accessed from within inner class; needs to be declared final
          meetingPromise = promise;
                           ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:284: error: local variable promise is accessed from within inner class; needs to be declared final
          promise.reject("ERR_UNEXPECTED_EXCEPTION", ex);
          ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:302: error: local variable promise is accessed from within inner class; needs to be declared final
            promise.reject("ERR_ZOOM_JOIN", "ZoomSDK has not been initialized successfully");
            ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:358: error: local variable promise is accessed from within inner class; needs to be declared final
          meetingPromise = promise;
                           ^
C:\Users\iskan\OneDrive\Desktop\Qubisa\qubisa-mobile-student\node_modules\react-native-zoom-us\android\src\main\java\ch\milosz\reactnative\RNZoomUsModule.java:371: error: local variable promise is accessed from within inner class; needs to be declared final
          promise.reject("ERR_UNEXPECTED_EXCEPTION", ex);
          
 i was using the [6.14.1] version

**Comment by amdrade** [comment]
I had the same error, after updating the gradle it worked, but only in the simulator

**Comment by mieszko4** [comment]
Please try with newest `6.16.5`.
