### ISSUE TITLE
Implementation into my app

### ISSUE THREAD

**Issue by akanz** [mieszko4/react-native-zoom-us#232]
Good day, 
I'm trying to integrate the zoom-us into my application. Do I need to also download the android and ios SDKs? What's the zoom access token also when I want to create a new meeting? 
Kindly looking forward to responses.

**Comment by amdrade** [comment]
there's the basics in this link [react-native-zoom-us-test](https://github.com/mieszko4/react-native-zoom-us-test)

**Comment by akanz** [comment]
Yeah I was able to figure it out eventually, thanks.
