### ISSUE TITLE
Metro server is not start after setup react-native-zoom-us (6.14.1 )

### ISSUE THREAD

**Issue by vijaykhandal1290** [mieszko4/react-native-zoom-us#234]
i am using these version-  
 "react": "18.0.0",
 "react-native": "0.69.5",
 "react-native-zoom-us": "^6.14.0",
 
 **I have all setup regarding zoom video integration after then this error will be  come on my mobile** 
 please anyone give me solution
 
 
![image](https://user-images.githubusercontent.com/113274246/189511928-8ff8999c-a299-4b0b-892d-eb52f3bbb04d.png)

**Comment by mieszko4** [comment]
Still an issue? Please try with newest `6.16.5`.
