### ISSUE TITLE
Using RN version:.0.68.2 and react-native-zoom-us:6.15.0.., still facing the issue "RNZoomUs Native Modules is not linked".., any update on this, please update if their is any plan for this fix

### ISSUE THREAD

**Issue by Abhinav1762** [mieszko4/react-native-zoom-us#238]
Using RN version:.0.68.2 and react-native-zoom-us:6.15.0.., still facing the issue "RNZoomUs Native Modules is not linked".., any update on this, please update if their is any plan for this fix

_Originally posted by @Abhinav1762 in https://github.com/mieszko4/react-native-zoom-us/issues/10#issuecomment-1265193579_

**Comment by mieszko4** [comment]
You can try either to use react-native 0.70 - the test app is updated now (https://github.com/mieszko4/react-native-zoom-us-test)

Or perhaps you forgot to do the 2nd step, i..e `SoLoader.loadLibrary("zoom"); // <-- ADD THIS LINE` in https://github.com/mieszko4/react-native-zoom-us/tree/v6.15.1#android
