### ISSUE TITLE
How to use this library with expo react-native android?

### ISSUE THREAD

**Issue by dysuryawanshi** [mieszko4/react-native-zoom-us#24]
Dear Team,
Please suggest me how to use this library with expo i have given package details please update me as soon as possible

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "~0.11.7",
    "react-native-zoom-bridge": "^1.0.18",
    "react-native-zoom-us": "^2.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}

**Comment by Yatanvesh** [comment]
I'm pretty sure you'll have to eject your project from expo.
This is a native module, which expo unfortunately does not support

**Comment by mieszko4** [comment]
Yeah, you cannot use it with expo unless it is ejected.
