### ISSUE TITLE
[iOS/Android] How to customize Zoom App Accessing Content Information in the UI

### ISSUE THREAD

**Issue by mrinmoysd** [mieszko4/react-native-zoom-us#244]
Hi,
Couple of questions I have regarding Zoom UI Customization.
Is there any way to hide the information on Zoom App Accessing Content that shows the app created in the zoom marketplace?
Can we overwrite the Camera and Microphone permission alert content, it occurs after installing the app and when we unmute or click on show video.

**Comment by mieszko4** [comment]
I am not sure
But if any of this is possible in [native iOS/Android Zoom SDKs](https://marketplace.zoom.us/docs/sdk/native-sdks/introduction/) then it should be possible to do here so I would check with their example apps.
