### ISSUE TITLE
Zoom join meeting not working

### ISSUE THREAD

**Issue by sarathdixit** [mieszko4/react-native-zoom-us#246]
When I try join the meeting it say joining, after that it redirects back to the app.

I'm using react-native 0.63.5 and react-native-zoom-us version is 5.1.0

**Comment by mj-iosdev** [comment]
@sarathdixit  Are you able to find any fix for this? I am facing the same issue. I am not receiving any error from `ZoomUs.joinMeeting` either. 

I am using version `6.0.4`

**Comment by hardikghanshyampatel** [comment]
I am facing similar issue throwing error from JNI

2022-11-21 12:39:55.000 8834-8834/com.getbundi A/com.getbundi: java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~SlCESx4uBMNznjmu1zE5mg==/com.getbundi-jF3XxjOP1WFuc_IFH7viAQ==/lib/arm64/libannotate.so"...
    java_vm_ext.cc:594]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1077)
    java_vm_ext.cc:594]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:998)
    java_vm_ext.cc:594]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1661)
    java_vm_ext.cc:594]   at void com.zipow.videobox.mainboard.module.ZmSdkMainBoard.loadSDKConfAppNativeModules() (ZmSdkMainBoard.java:8)
    java_vm_ext.cc:594]   at void com.zipow.videobox.mainboard.module.ZmSdkMainBoard.createConfAppForSdk(java.lang.String) (ZmSdkMainBoard.java:8)
    java_vm_ext.cc:594]   at void com.zipow.videobox.VideoBoxApplication.initConfAppForSDK(java.lang.String) (VideoBoxApplication.java:23)
    java_vm_ext.cc:594]   at int com.zipow.videobox.VideoBoxApplication.startConfServiceForSDK(android.os.Bundle) (VideoBoxApplication.java:8)
    java_vm_ext.cc:594]   at int com.zipow.videobox.ptapp.ConfProcessMgr.createConfProcess(java.lang.String) (ConfProcessMgr.java:13)
    java_vm_ext.cc:594]   at void com.zipow.videobox.mainboard.Mainboard.notifyUrlActionImpl(java.lang.String) (Mainboard.java:-2)
    java_vm_ext.cc:594]   at void com.zipow.videobox.mainboard.Mainboard.notifyUrlAction(java.lang.String) (Mainboard.java:5)
    java_vm_ext.cc:594]   at int com.zipow.videobox.confapp.meeting.premeeting.joinscene.ZMJoinByUrl.joinByUrl(android.content.Context, java.lang.String, java.lang.String, boolean) (ZMJoinByUrl.java:62)
    java_vm_ext.cc:594]   at int com.zipow.videobox.confapp.meeting.premeeting.joinscene.ZMJoinByUrl.joinByUrl(android.content.Context, java.lang.String, boolean) (ZMJoinByUrl.java:44)
    java_vm_ext.cc:594]   at int com.zipow.videobox.confapp.meeting.premeeting.joinscene.ZMJoinByUrl.startConfrence(android.content.Context) (ZMJoinByUrl.java:3)
    java_vm_ext.cc:594]   at boolean com.zipow.videobox.JoinByURLActivity.a(android.net.Uri, boolean) (JoinByURLActivity.java:13)
    java_vm_ext.cc:594]   at boolean com.zipow.videobox.JoinByURLActivity.a(android.net.Uri, boolean, boolean) (JoinByURLActivity.java:41)
    java_vm_ext.cc:594]   at void com.zipow.videobox.JoinByURLActivity.b(android.net.Uri, boolean) (JoinByURLActivity.java:44)
    java_vm_ext.cc:594]   at void com.zipow.videobox.JoinByURLActivity.onResume() (JoinByURLActivity.java:133)
    java_vm_ext.cc:594]   at void android.app.Instrumentation.callActivityOnResume(android.app.Activity) (Instrumentation.java:1491)
    java_vm_ext.cc:594]   at void android.app.Activity.performResume(boolean, java.lang.String) (Activity.java:8296)
    java_vm_ext.cc:594]   at boolean android.app.ActivityThread.performResumeActivity(android.app.ActivityThread$ActivityClientRecord, boolean, java.lang.String) (ActivityThread.java:4933)
    java_vm_ext.cc:594]   at void android.app.ActivityThread.handleResumeActivity(android.app.ActivityThread$ActivityClientRecord, boolean, boolean, java.lang.String) (ActivityThread.java:4990)
    java_vm_ext.cc:594]   at void android.app.servertransaction.ResumeActivityItem.execute(android.app.ClientTransactionHandler, android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions) (ResumeActivityItem.java:60)
    java_vm_ext.cc:594]   at void android.app.servertransaction.ActivityTransactionItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (ActivityTransactionItem.java:45)
    java_vm_ext.cc:594]   at void android.app.servertransaction.TransactionExecutor.executeLifecycleState(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:176)

**Comment by mj-iosdev** [comment]
> @sarathdixit Are you able to find any fix for this? I am facing the same issue. I am not receiving any error from `ZoomUs.joinMeeting` either.
> 
> I am using version `6.0.4`

Updating package to latest version seems to fix this issue for me.
