### ISSUE TITLE
Hls videos are not getting played, after updating to new zoom sdk version.

### ISSUE THREAD

**Issue by shivnativehealth** [mieszko4/react-native-zoom-us#249]
Hello, In my react native project i am using both **expo-av** and **react-native-zoom-us** together. Things were working with the older versions. But now, zoom sessions i am able to open but videos playback using expo-av is not working, it keeps on loading. Have posted same issue in expo github page in search of some help (https://github.com/expo/expo/issues/20525). Any insights or help will be greatly appreciated. Thanks.

Older versions:
expo-av: 10.2.0
react-native-zoom-us: 6.6.1

Newer version:
expo-av: 10.2.0(no changed )
react-native-zoom-us: 6.14.1

**Issue:** 
Any hls or static videos are not getting played with the library expo-av. Have posted this issue in the expo-av github section as well. But thought of reposting here, since it started coming after updating the zoom sdk version.

Any help or insights will be appreciated. Thanks.

**Comment by mieszko4** [comment]
Please try with newest `6.16.5`.

**Comment by mieszko4** [comment]
Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.
