### ISSUE TITLE
Zoom sdk crashing on android 

### ISSUE THREAD

**Issue by shivnativehealth** [mieszko4/react-native-zoom-us#250]
Hello, we are using this sdk since long for zoom calls. But due to some crashes on android 12 we tried to update it to the new version 6.15.1, and now we are getting some weird crashes (added screenshot of the crash from firebase crashlytics). 
![Screenshot 2022-12-22 at 11 41 32 AM](https://user-images.githubusercontent.com/113965106/209069334-afd12013-7e44-4655-a6ec-ccf99bd0ba6a.png)

Just for additional info, if required to know: 
We are using expo-av(https://www.npmjs.com/package/expo-av) in our project as well which also uses exo player similar to react-native-zoom sdk.

Any help will be greatly appreciated.

Thanks.

**Comment by priyamego123** [comment]
Getting the same issue, any solution on it

**Comment by mieszko4** [comment]
May be related to https://github.com/mieszko4/react-native-zoom-us/issues/230. Please try with newest `6.16.5`.

**Comment by chirag-codealchemy** [comment]
https://github.com/chirag-codealchemy/zoom-test

it's my repo with minimum example app which crashes

note:- my app on crash on devices android 12 and above

**Comment by mieszko4** [comment]
I see you are using older rn (`"react-native": "0.65.3",`).
Perhaps try to upgrade it to at least `0.70.12`

**Comment by mieszko4** [comment]
I am closing this due to https://github.com/mieszko4/react-native-zoom-us-test/issues/70 (I tested [test app](https://github.com/mieszko4/react-native-zoom-us-test) on Android 13)
