### ISSUE TITLE
Your current SDK will be deprecated in Feb-4 so did you work on the update?

### ISSUE THREAD

**Issue by chirag-codealchemy** [mieszko4/react-native-zoom-us#253]
Your current SDK will be deprecated in Feb-4 so did you work on the update?
check this link ---> https://marketplace.zoom.us/docs/sdk/overview/minimum-version/

**Comment by mieszko4** [comment]
Thnx for opening this issue! We got stuck on upgrading Android Zoom SDK (https://github.com/mieszko4/react-native-zoom-us/pull/219). But I will try with newest version. Hopefully will be fine :)

**Comment by chirag-codealchemy** [comment]
i got this Error from your feat/upgrade-android-to-5.11.0.6883 repo
dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~dMmAyVZfqTq1iae5l3BSwA==/com.collegepass-0rt1XzBebDX361V7Be7qRw==/lib/x86_64/libannotate.so"... java_vm_ext.cc:594]   at void

can you please... fix this ASAP

**Comment by wilkinson4** [comment]
Also curious about this because we are in the process of implementing the Zoom Meeting SDK into our RN app. I saw that your referenced issue was from June 2022, and I know there have been some improvements to M1 compatibility since then.

**Comment by mieszko4** [comment]
Unfortunately, I am not sure what it is (not an expert in Android).

Anyway, I tried to update to 5.12.8 - it did not help; app was crashing when joining the meeting
I also tried to update to 5.13.1 - app crashes on init

I will need more time to figure this out.

**Comment by mieszko4** [comment]
Fixed with newest version - 6.16.4. Make sure to see [breaking changes](https://github.com/mieszko4/react-native-zoom-us/blob/master/CHANGELOG.md#6160)
Also updated [test app](https://github.com/mieszko4/react-native-zoom-us-test)
Also created issue for [automating copying of *.aar files](https://github.com/mieszko4/react-native-zoom-us/issues/257)
