### ISSUE TITLE
error: package us.zoom.sdk does not exist

### ISSUE THREAD

**Issue by cloudy-ninja** [mieszko4/react-native-zoom-us#258]
I upgraded the version to the latest one 6.16.4 and the iOS is working well, but I'm not able to build the Android part. I just followed the readme including adding both commonlib and mobilertc into the folder of node_modules/react-native-zoom-us. 
While building the app, I got lots of error related to importing us.zoom.sdk

@mieszko4 could you please let me know what's wrong on my side?

**Comment by cloudy-ninja** [comment]
![Screenshot 2023-02-07 at 16 04 21](https://user-images.githubusercontent.com/29693240/217365198-f1595d58-fcc2-4cf5-aef9-90953fd963e2.png)

**Comment by cloudy-ninja** [comment]
![Screenshot 2023-02-07 at 16 05 02](https://user-images.githubusercontent.com/29693240/217365323-5e4c3b16-e425-4d46-9634-290b37e16f38.png)

**Comment by mieszko4** [comment]
You need to manually copy *.aar files. I was not able to push *.aar files to [jitpack](https://github.com/zoom-us-community/jitpack-zoom-us) because of LFS limit reached :( And I did not have time to automate this (I created issue to automate https://github.com/mieszko4/react-native-zoom-us/issues/257)

See https://github.com/mieszko4/react-native-zoom-us#getting-started for instructions how to manually add *.aar files.

**Comment by cloudy-ninja** [comment]
Hi, @mieszko4  Thanks for your reply and efforts, Yes, I already added these two files to the root of react-native-zoom-us module, see the attached screenshot.

**Comment by cloudy-ninja** [comment]
![Uploading Screenshot 2023-02-07 at 18.51.44.png…]()

**Comment by cloudy-ninja** [comment]
After adding the *.aar files like this, got the above error. Instead, I added them separately to the folders commonlib and mobilertc inside the android folder. I don't know I misunderstood the readme file

**Comment by cloudy-ninja** [comment]
![Screenshot 2023-02-07 at 18 51 44](https://user-images.githubusercontent.com/29693240/217394529-7ee57068-1689-4d53-9c71-02b7a85f72fe.png)

**Comment by cloudy-ninja** [comment]
![Screenshot 2023-02-07 at 18 55 33](https://user-images.githubusercontent.com/29693240/217394616-52724cff-5e8a-4aa2-92da-304dffe30ebc.png)

**Comment by cloudy-ninja** [comment]
![Screenshot 2023-02-07 at 18 33 32](https://user-images.githubusercontent.com/29693240/217394664-97db3e0b-8b53-4512-8257-fd74f584494b.png)

**Comment by mieszko4** [comment]
> ![Screenshot 2023-02-07 at 18 55 33](https://user-images.githubusercontent.com/29693240/217394616-52724cff-5e8a-4aa2-92da-304dffe30ebc.png)

Yes, this is the final state of where these *.aar should be placed to.

The instructions may be confusing - feel free to make a PR to improve them.

I see you added *.aar of the root of react-native-zoom-us. They should be added in the **root of your project** before installing react-native-zoom-us.

But again, you manage to get this part correctly now.

**Comment by mieszko4** [comment]
> ![Screenshot 2023-02-07 at 18 33 32](https://user-images.githubusercontent.com/29693240/217394664-97db3e0b-8b53-4512-8257-fd74f584494b.png)

:thinking: I am not sure what the problem is here. Perhaps some collision with react-native-video...

**Comment by cloudy-ninja** [comment]
@mieszko4 Thanks for your confirmation, I don't think this specific issue is related to our zoom lib. So I'm gonna close this ticket. Have a good day!
