### ISSUE TITLE
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by shafqatbari** [mieszko4/react-native-zoom-us#260]
I have followed the Documentation but I am not able to run the Project

[https://www.npmjs.com/package/react-native-zoom-us](https://www.npmjs.com/package/react-native-zoom-us)

    "react": "18.1.0",
    "react-native": "0.70.0",
    "react-native-zoom-us": "^6.16.4",

      android/build.gradle
        minSdkVersion = 23
        compileSdkVersion = 32
        targetSdkVersion = 31

I am facing this Error when I run "npx react-native run-android"

`Note: Recompile with -Xlint:unchecked for details.
/Volumes/ReporteqProjects/MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:76: error: RNZoomUsModule is not abstract and does not override abstract method onLocalRecordingPrivilegeRequested(IRequestLocalRecordingPrivilegeHandler) in InMeetingServiceListener
public class RNZoomUsModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, InMeetingServiceListener, MeetingServiceListener, InMeetingShareController.InMeetingShareListener, LifecycleEventListener {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

/Volumes/ReporteqProjects/MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:76: error: RNZoomUsModule is not abstract and does not override abstract method onLocalRecordingPrivilegeRequested(IRequestLocalRecordingPrivilegeHandler) in InMeetingServiceListener
public class RNZoomUsModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, InMeetingServiceListener, MeetingServiceListener, InMeetingShareController.InMeetingShareListener, LifecycleEventListener {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

`

**Comment by shafqatbari** [comment]
`
> Task :react-native-zoom-us:compileDebugJavaWithJavac FAILED

> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
176 actionable tasks: 7 executed, 169 up-to-date
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsActivity.java:4: warning: [deprecation] MeetingActivity in us.zoom.sdk has been deprecated
import us.zoom.sdk.MeetingActivity;
                  ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:76: error: RNZoomUsModule is not abstract and does not override abstract method onLocalRecordingPrivilegeRequested(IRequestLocalRecordingPrivilegeHandler) in InMeetingServiceListener
public class RNZoomUsModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, InMeetingServiceListener, MeetingServiceListener, InMeetingShareController.InMeetingShareListener, LifecycleEventListener {
       ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:1122: warning: [deprecation] onShareActiveUser(long) in InMeetingShareListener has been deprecated
  public void onShareActiveUser(long userId) {
              ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:209: warning: [deprecation] Integer(int) in Integer has been deprecated
      videoViews.add(new Integer(tagId));
                     ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:219: warning: [deprecation] Integer(int) in Integer has been deprecated
      videoViews.remove(new Integer(tagId));
                        ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsVideoView.java:61: warning: [deprecation] Long(long) in Long has been deprecated
      users.remove(new Long(inMeetingService.getMyUserID()));
                   ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsActivity.java:6: warning: [deprecation] MeetingActivity in us.zoom.sdk has been deprecated
public class RNZoomUsActivity extends MeetingActivity {
                                      ^
1 error
6 warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/activity_media_player.xml:7: AAPT: error: attribute controller_layout_id (aka com.salushealth:controller_layout_id) not found.`

**Comment by shafqatbari** [comment]
This is the all errors. Please anyone have the solution? then please share . When I used the 
"react-native-zoom-us": "^5.0.0",
the the Sdk was intialized but on Join meeting it was not working and App crashes So I tried to  use the Latest version now its not working

**Comment by mieszko4** [comment]
Please try with newest `6.16.5`. May be related to [deprecation of SDK](https://marketplace.zoom.us/docs/sdk/overview/minimum-version/). Also see [test app](https://github.com/mieszko4/react-native-zoom-us-test).

**Comment by shafqatbari** [comment]
@mieszko4 I have checked that Its Working
