### ISSUE TITLE
Join meeting crashed the app on android

### ISSUE THREAD

**Issue by paingpyaethu** [mieszko4/react-native-zoom-us#268]
When i use version 6.16.4, it works. But can't build assembleRelease. When i use latest version 6.16.5, the app crash. Is any other solution for version 6.16.4? or how to fix app crash problem in latest version please?...

**Comment by amdrade** [comment]
Same error, on Android 10 works, Android 12 not works.
version 6.16.5

**Comment by ampraveeen** [comment]
I am facing the same issue. Did you found any solution?

**Comment by amdrade** [comment]
Workaround!
Downgrade to **6.16.3** and add the Zoom SDK manually

- Android: 5.13.1
- iOS: 5.11.3

**Comment by rahulvyas** [comment]
> 6.16.3

Can you share the steps?

**Comment by rahulvyas** [comment]
> Workaround! Downgrade to **6.16.3** and add the Zoom SDK manually
> 
> * Android: 5.13.1
> * iOS: 5.11.3

I am getting a black screen only

**Comment by amdrade** [comment]
what version of react-native?
I'm using 0.62.2

**Comment by keshav-raj** [comment]
We were also facing the same issue after upgrading latest react native V0.71.7 issues get resolved, I guess upgrading build tool will solve the issue

**Comment by rahulvyas** [comment]
> what version of react-native? I'm using 0.62.2

    "react-native": "0.68.0",

**Comment by Denesvargas** [comment]
> When i use version 6.16.4, it works. But can't build assembleRelease. When i use latest version 6.16.5, the app crash. Is any other solution for version 6.16.4? or how to fix app crash problem in latest version please?...

Same situation here. assembleRelease don't work in Android 11 with 6.16.4 and 6.15.5 the app crash, I was using react-native 0.68.7 and upgraded to 0.70.5 as described in Readme, but without success.

I'm getting the errors above when trying to assembleRelease with manual installation (6.16.3 or 6.16.4):

Execution failed for task ':react-native-zoom-us:bundleReleaseLocalLintAar'.
\> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-zoom-us:bundleReleaseLocalLintAar'
       \> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because...

**Comment by amdrade** [comment]
> We were also facing the same issue after upgrading latest react native V0.71.7 issues get resolved, I guess upgrading build tool will solve the issue

Hello, can you share your build.gradle settings?
We made that update here, but it didn't work. :(
