### ISSUE TITLE
Is lottie dependency needed?

### ISSUE THREAD

**Issue by smikheiev** [mieszko4/react-native-zoom-us#270]
Hi! I noticed that there's `com.airbnb.android:lottie:4.0.0` dependency in `build.gradle`. I didn't find any usage of `lottie` in the project, so I wonder if the dependency is needed 🤔

**Comment by amdrade** [comment]
It's a Zoom dependency

[Integrate with your app](https://developers.zoom.us/docs/meeting-sdk/android/get-started/integration/#1-locate-the-libraries)

**Comment by smikheiev** [comment]
oh, I see, thanks for pointing out @amdrade!
I also noticed that `lottie` dependency is added twice - on L40 and L62 (https://github.com/mieszko4/react-native-zoom-us/blob/master/android/build.gradle#L40). I suppose one of them can be removed 🤓
