### ISSUE TITLE
Meeting SDK app types created after February 11, 2023 have one set of credentials

### ISSUE THREAD

**Issue by chirag-codealchemy** [mieszko4/react-native-zoom-us#271]
![Screenshot 2023-05-10 at 10 05 05 AM](https://github.com/mieszko4/react-native-zoom-us/assets/111970008/9028d31a-8357-4002-a634-1346eca9defb)

https://developers.zoom.us/docs/meeting-sdk/auth/#generate-a-meeting-sdk-jwt

**Comment by amdrade** [comment]
[initialize using JWT](https://github.com/mieszko4/react-native-zoom-us#usage)

`await ZoomUs.initialize({
  jwtToken: '...',
})
`

**Comment by mieszko4** [comment]
Not sure what this issue is about.
As @amdrade mentioned, we can only use `jwtToken` now - it is enforced in react-native-zoom-us@6.20.0
