### ISSUE TITLE
react-native-zoom-us throwing error code 4.

### ISSUE THREAD

**Issue by Sharan0219** [mieszko4/react-native-zoom-us#273]
I've integrated react-native-zoom-us package to join meetings from my app. Although it does get initialised correctly, but after that it throws this error "[Error: Error: 4, internalErrorCode=0]".
<img width="1265" alt="Screenshot 2023-05-12 at 12 22 25 PM" src="https://github.com/mieszko4/react-native-zoom-us/assets/115989625/36d18f80-dc31-4c19-945a-c311523955bf">

**Comment by poonamyadav-kiwi** [comment]
I am facing the same issue on both the versions 6.15.1 and 6.16.5 only on android working fine for ios

**Comment by khuongphp** [comment]
@poonamyadav-kiwi 
You can upgrade react-native to 0.71.3 or higher to fix this. Or wait other ideas from community
