### ISSUE TITLE
Android App crashing when ZoomUs.startMeeting call

### ISSUE THREAD

**Issue by vijaykhandal1290** [mieszko4/react-native-zoom-us#275]
Android app is crashing while zoom start meeting and join meeting. Perfectly working in IOS

"react-native": "0.70.6",
"react-native-zoom-us": "^6.16.5",

**Comment by ahmedraza42** [comment]
facing same issue on android for few days ,working fine on ios
Although before few days, my app working fine on both platform and current live on both store

**Comment by vijaykhandal1290** [comment]
@ahmedraza42 Please update your react native version 0.71.3 and also update zoom library.
It will work.

**Comment by ahmedraza42** [comment]
@vijaykhandal1290  which gradle version you use ? mine is: classpath("com.android.tools.build:gradle:7.0.4")

i got an error: after upgrading react native to 0.71.3

> Task :react-native-gradle-plugin:compileKotlin FAILED
1 actionable task: 1 executed
e: /Users/Ahmed/Desktop/Project/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt: (138, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'

**Comment by vijaykhandal1290** [comment]
@ahmedraza42 Please update pour code properly on android native and IOS native also.

**Comment by ahmedraza42** [comment]
Thanks @vijaykhandal1290  you saved my day

**Comment by shanusingh3** [comment]
@vijaykhandal1290 when I'm trying to call joinMeeting nothing happens, any idea in iOS?

**Comment by mieszko4** [comment]
> @vijaykhandal1290 when I'm trying to call joinMeeting nothing happens, any idea in iOS?

Perhaps you could try 6.17.0 - just upgraded Zoom SDK on iOS
