### ISSUE TITLE
Error type 3, just after installing the app

### ISSUE THREAD

**Issue by heyarviind** [mieszko4/react-native-zoom-us#276]
I am getting this error just after the app is installed on the device and it tries to start:

```
info Connecting to the development server...
info Starting the app on "936X1XH13"...
Starting: Intent { cmp=ch.milosz.reactnative/.MainActivity }
Error type 3
Error: Activity class {ch.milosz.reactnative/ch.milosz.reactnative.MainActivity} does not exist.
```

I have tried deleting the build folder, cleaning the project, invalidating the cache, and again building the app (as mentioned on the StackOverflow and GitHub discussions) with no success.

Platform: Android

**Comment by mieszko4** [comment]
Is test app working for you? (https://github.com/mieszko4/react-native-zoom-us-test)

**Comment by mieszko4** [comment]
Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.
