### ISSUE TITLE
no callback is getting fired when calling joinMeeting from iOS

### ISSUE THREAD

**Issue by shanusingh3** [mieszko4/react-native-zoom-us#277]
Hi, 

I'm trying to run join a meeting from an iOS device, with a hardcoded meeting ID and password, at the beginning SDK throws an error but after some time it is initialized. When I try to call to join the meeting, **Promise returns nothing**, and stays on the same screen.

**Comment by mieszko4** [comment]
Could you try with 6.17.0 (it has upgraded Zoom SDK for iOS)

**Comment by mieszko4** [comment]
Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.
