### ISSUE TITLE
Upgrade Android SDK to at least 5.13.11

### ISSUE THREAD

**Issue by mieszko4** [mieszko4/react-native-zoom-us#280]
Closes https://github.com/mieszko4/react-native-zoom-us-test/issues/66
Related https://github.com/mieszko4/react-native-zoom-us-test/issues/27#issuecomment-1598241383

Maybe closes https://github.com/mieszko4/react-native-zoom-us-test/issues/65

**Comment by ccdwyer** [comment]
@mieszko4 Is there anything you need help with to help make this happen before August 5th?

**Comment by mieszko4** [comment]
I just need some time to complete this.
If anyone else wants to do it then I am of course open for PRs.
Otherwise, I will try at the end of this week :)

**Comment by AwabIjaz** [comment]
any update on this ?

**Comment by ajayhcode** [comment]
any update ??
