### ISSUE TITLE
Zoom iOS SDK 5.13.10.7064 Webinar Crash

### ISSUE THREAD

**Issue by wstuckmeyer** [mieszko4/react-native-zoom-us#285]
The current minimum required SDK for iOS has a bug that causes Webinars to crash when joining.  I believe this issue wasn't fixed until SDK 5.14.10 onwards. I've attached a forum discussion from the Zoom forum discussing the issue. Can we get the iOS version bumped to a version that doesn't have this bug?

[https://devforum.zoom.us/t/discussion-crash-on-joining-webinar-in-ios-meeting-sdk-version-5-13-10-7064-and-above/86524/8](url)

**Comment by mieszko4** [comment]
Yes, would be great to upgrade to `5.14.11` both Android and iOS.
I am not sure when I will find time for that though.

**Comment by mieszko4** [comment]
I created https://github.com/mieszko4/react-native-zoom-us/issues/290 and https://github.com/mieszko4/react-native-zoom-us/issues/291

**Comment by shayan-o16labs** [comment]
Please ugrade this library both IOS and Android @mieszko4

**Comment by rahulvyas** [comment]
@mieszko4 Please upgrade both iOS and android library. We're having crash on both iOS and Android.

**Comment by mieszko4** [comment]
Please try with react-native-zoom-us@6.20.0 (with updated ZoomSDK to 5.14.11.8690)
