### ISSUE TITLE
noInvite,noTitlebar,noTextMeetingId,noTextPassword not working in ios

### ISSUE THREAD

**Issue by RangaAjay** [mieszko4/react-native-zoom-us#286]
noInvite,noTitlebar,noTextMeetingId,noTextPassword not working in ios
These options are only working in android only

**Comment by mieszko4** [comment]
Yes, these options are currently only implemented on Android.

**Comment by ajayhcode** [comment]
Kindly at this in readme. As this will be ambiguous for users

**Comment by mieszko4** [comment]
iOS/Android only fields are mentioned in https://github.com/mieszko4/react-native-zoom-us/blob/master/index.ts but I agree it would be great to have it written more strict. Ideally it would be great to have it integrated with typescript so that when I type function name then I see that the restriction.

**Comment by ajayhcode** [comment]
@mieszko4 @jcamins @mialy @hans00 Is there any way to stop sharing meeting link in IOS just like android. Without using custom UI.

**Comment by mialy** [comment]
@ajayhcode Please stop tagging me.

**Comment by ajayhcode** [comment]
> @ajayhcode Please stop tagging me.

ok

**Comment by ajayhcode** [comment]
> @mieszko4 @jcamins @hans00 Is there any way to stop sharing meeting link in IOS just like android. Without using custom UI.

is there any way

**Comment by mieszko4** [comment]
Not that I am aware of. If it is not in https://marketplacefront.zoom.us/sdk/meeting/ios/annotated.html then there is no way.

There is [meetingInviteHidden](https://marketplacefront.zoom.us/sdk/meeting/ios/interface_mobile_r_t_c_meeting_settings.html#a58df8b82a962603c9b513d7875a25f4a) but it is only for Custom UI
![image](https://github.com/mieszko4/react-native-zoom-us/assets/3238370/95d2af30-83cb-43bb-a63a-20202889eda6)

**Comment by mieszko4** [comment]
Related issue for custom iOS UI - https://github.com/mieszko4/react-native-zoom-us/issues/113
