### ISSUE TITLE
Upgrade iOS to 5.14.11

### ISSUE THREAD

**Issue by mieszko4** [mieszko4/react-native-zoom-us#290]

**Comment by zvs001** [comment]
I pushed new sdk versions:
5.16.5.11131
5.15.12.10118  
5.14.11.8690

**Comment by rahulvyas** [comment]
> I pushed new sdk versions: 5.16.5.11131 5.15.12.10118   5.14.11.8690

How we can use new SDK versions until @mieszko4 updates the react-native version?

**Comment by zvs001** [comment]
you need to patch this file: https://github.com/mieszko4/react-native-zoom-us/blob/master/RNZoomUs.podspec#L22

New version might require some minor library alignment, so not sure if you can use it without library update.

**Comment by rahulvyas** [comment]
Thanks for the update. Let's wait for @mieszko4 to update the react-native side code and update both android and iOS libraries to a stable one. I am really stuck into this from a long time :(. The app is crashing on android 12 and above also in iOS it's crashing immediately leaving very bad experience for users.

**Comment by zvs001** [comment]
@rahulvyas If it is urgent, I would recommend to try to update lib. Code examples also can be found in zoomsdk file. Otherwise, we don't know how long it will take until we will see update

**Comment by rahulvyas** [comment]
@zvs001 Yes, You're right it's kinda urgent. Let me know how I can patch it and update the iOS SDK. Is there anything I need to change in library's code? If yes please guide me how I can do that in react-native side as you've wrote that "New version might require some minor library alignment, so not sure if you can use it without library update". Also any hint to update android one too?

**Comment by zvs001** [comment]
@rahulvyas 
1) clone this repository and link it to your project.
2) change sdk version

try to compile and you will see errors. 
I expect errors like missing implementation or type is different. These errors you can solve by copying this code from zoom example to this library. (it is inside zip archive in zoomsdk. you can find sdk at zoom app settings)
Maybe there will be something else. I don't know.

**Comment by rposborne** [comment]
@mieszko4 As we hit 2 weeks out from the next min SDK enforcement by zoom. What can we do to support getting this bump? 

https://developers.zoom.us/docs/meeting-sdk/minimum-version/

**Comment by mieszko4** [comment]
react-native-zoom-us@6.20.0 released.
