### ISSUE TITLE
Please join this meeting with official zoom meeting client (error code:6601) what is the meaning of this error

### ISSUE THREAD

**Issue by ramanguptazelhus** [mieszko4/react-native-zoom-us#293]
Hi Sir,
I'm using react-native-zoom-us package version **6.8.1** So I got this error *: --- Please join this meeting with the official Zoom meeting client (error code:6601) on Join the meeting 
@mieszko4 @jcamins @mialy @mieszko4 @amdrade   **URGENT**

**Comment by amdrade** [comment]
See if this can help you.
[potential-unity-integration-with-zoom-android-sdk](https://devforum.zoom.us/t/potential-unity-integration-with-zoom-android-sdk/92911/2?u=fernando.moobi)

` 6601 ← this error is related to joining a meeting outside of the account.`

**Comment by ramanguptazelhus** [comment]
Hi,
I still got this error.

**Comment by ramanguptazelhus** [comment]
> See if this can help you. [potential-unity-integration-with-zoom-android-sdk](https://devforum.zoom.us/t/potential-unity-integration-with-zoom-android-sdk/92911/2?u=fernando.moobi)
> 
> ` 6601 ← this error is related to joining a meeting outside of the account.`

**Comment by ramanguptazelhus** [comment]
How to solve this error ?

Error joining meeting:  Error: Error: 4, internalErrorCode=0

Any solution?

**Comment by mieszko4** [comment]
Please try with react-native-zoom-us@6.20.0 and re-open this issue if you still have a problem.
