### ISSUE TITLE
After Preparing meeting... screen it is going back 

### ISSUE THREAD

**Issue by ramanguptazelhus** [mieszko4/react-native-zoom-us#294]
@After Preparing meeting... screen it is going back ?

Any Solution ?
why it's happening?

@jcamins  @mialy  @hans00 @mieszko4 @jcamins

**Comment by amdrade** [comment]
does it show any error?

**Comment by ramanguptazelhus** [comment]
Thanks for replying, but everything is working fine.Message ID:
> ***@***.***>
>

**Comment by ramanguptazelhus** [comment]
Hi,

I am writing to you today to ask about the safety of your package react-native-zoom-us for integrating into my React Native client-side project.

I am developing a React Native app that will use react-native-zoom-us for Zoom Meeting Integration. I believe that react-native-zoom-us is the perfect solution for my needs, but I want to make sure that it is safe to use before I integrate it into my project.

I have read the documentation for react-native-zoom-us and it seems to be well-written and well-maintained. However, I want to make sure that it is not vulnerable to any security risks.

Can you provide me with any information about the security of react-native-zoom-us? For example, has it been audited for security vulnerabilities? Are there any known security risks associated with it?

I would be grateful for any information you can provide me. I am confident that react-native-zoom-us is a great package, but I want to make sure that it is safe to use before I integrate it into my client-side project.

@amdrade @jcamins @mialy @hans00

Thanks

**Comment by mieszko4** [comment]
> Can you provide me with any information about the security of react-native-zoom-us? For example, has it been audited for security vulnerabilities? Are there any known security risks associated with it?

This lib is just a bridge for ZoomUs SDK.
We do not audit the package and we cannot guarantee any security - it is an open-source project so feel free to contribute with auditing the package.

> Preparing meeting... screen it is going back ?

We just updated iOS and Android packages. 
Please try with react-native-zoom-us@6.20.0.
