### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ramangupta1602** [mieszko4/react-native-zoom-us#295]
Hi @jcamins @mialy @hans00 @amdrade 

**meetingClientIncompatible** got this error when I joined Zoom Meeting.

Thanks

**Comment by AhmedAliEldiasty1** [comment]
@ramangupta1602 I have a crash when I try to join meeting in android only, is this like you?

**Comment by ramangupta1602** [comment]
@AhmedAliEldiasty1, I'm trying in Android now.

**Comment by shayan-o16labs** [comment]
@ramangupta1602 Android is working fine but in IOS is not working fine did you solve this issue?

**Comment by mieszko4** [comment]
Please try with react-native-zoom-us@6.20.0
