### ISSUE TITLE
Where is your commonlib and moiblertc file in the folder structure

### ISSUE THREAD

**Issue by ramanguptazelhus** [mieszko4/react-native-zoom-us#296]
Hi @mieszko4 @jcamins @mialy @hans00 @amdrade ,

How do you integrate Zoom meeting SDK in react-native? I saw your Android folder, but I did not get the commonlib and moiblertc file.

**Comment by amdrade** [comment]
Download by jitpack. In previous versions, you had to copy these files manually.
[android/build.gradle#L38C5-L38C80](https://github.com/mieszko4/react-native-zoom-us/blob/6caa7c0360a8ac2e72acf57b67be5939ad40a7db/android/build.gradle#L38C5-L38C80)

**Comment by ramanguptazelhus** [comment]
@amdrade 
So, If I download jitpack then I have not to add commonlib and mobilertc file in android folder ?

**Comment by amdrade** [comment]
That's it, the download is done automatically.

**Comment by ramanguptazelhus** [comment]
@amdrade
I want to decrease apk and aab file size.

**Comment by mieszko4** [comment]
> @amdrade I want to decrease apk and aab file size.

You can try with https://github.com/mieszko4/react-native-zoom-us/blob/e2fe546f2ffe1992cb6ed4bc779897e28a436718/docs/SIZE-REDUCTION-TIPS.md but that guide might be outdated. Feel free to make a PR if you will see that somethings need to be updated.
