### ISSUE TITLE
Error : --------

### ISSUE THREAD

**Issue by ramanguptazelhus** [mieszko4/react-native-zoom-us#297]
Hi @jcamins @mialy @hans00 @mieszko4 @amdrade,

I encountered an error when attempting to join or start the meeting.
[Error: Error: 100, internalErrorCode=6601]

**Comment by amdrade** [comment]
@ramanguptazelhus see
[Meeting STATUS: FAILED, error= 100, internal error= 6601](https://devforum.zoom.us/t/potential-unity-integration-with-zoom-android-sdk/92911/2)

> Meeting STATUS: FAILED, error= 100, internal error= 6601 ← this error is related to joining a meeting outside of the account. If the SDK is trying to join an meeting hosted outside of the account, this error will be thrown.
