### ISSUE TITLE
How can I change icon shown before video starting

### ISSUE THREAD

**Issue by chelenli** [mieszko4/react-native-zoom-us#298]
Is there a way to change or remove this icon 

![rabbt](https://github.com/mieszko4/react-native-zoom-us/assets/32742819/8eaccb75-fb42-4a43-9592-83ec06dc76ee)

**Comment by mieszko4** [comment]
Please provide more context.
AFAIK, this icon is not part of Zoom SDK and it is definitely not part of react-native-zoom-us.
