### ISSUE TITLE
Error When join a meeting

### ISSUE THREAD

**Issue by shayan-o16labs** [mieszko4/react-native-zoom-us#299]
Hi @jcamins @mialy @hans00 @mieszko4 @amdrade,

I encountered an error when attempting to join or start the meeting.
Error: 10, internalErrorCode=the mobilertc version is incompatible

**Comment by shayan-o16labs** [comment]
Please help  @jcamins @mialy @hans00 @mieszko4 @amdrade,

**Comment by amdrade** [comment]
:( unfortunately I don't know object-c, you can try the [zoom forum](https://devforum.zoom.us/c/meeting-sdk/ios/12). It's already helped me a lot, even though it's not react-native.

**Comment by mieszko4** [comment]
Not sure why it shows for you. I haven't tested the lib on macOS (only Android and iPhone).
Please try with react-native-zoom-us@6.20.0 - that might help.
