### ISSUE TITLE
App is crashing in zoom initialize process 

### ISSUE THREAD

**Issue by ahmedsu** [mieszko4/react-native-zoom-us#3]
I have problem when I want to initialize zoom. App is crashing. Any suggestions? Also tried your zoom-us test project.

**Comment by mieszko4** [comment]
I haven't checked this project for 9 months.
I suppose you are using new android/iso but there could be lots of reasons. Please be more specific why app is crashing. Write some logs, etc.

**Comment by ahmedsu** [comment]
I'll check some logs now and deliver it. I am was trying it with API Level 27 and 28. 27 API Level is max supported by Zoom as I can see. But in both of them it just put app down when I call ZoomUs.initialize function. With no error displayed. And I get alert "App is crashed." from Android OS.

**Comment by ahmedsu** [comment]
When I try to initialize Zoom this happens: 

![zoominiti](https://user-images.githubusercontent.com/20888827/57782585-d823c500-772c-11e9-828b-ee6a9a871c93.PNG)

This is when I try to start it with press on a button but Zoom is not initialized:

![zoomstart](https://user-images.githubusercontent.com/20888827/57782614-e1ad2d00-772c-11e9-8a02-99730465b0b5.PNG)

**Comment by mieszko4** [comment]
I upgraded the lib to `v2` with newest android zoom sdk.
The demo for this is in branch https://github.com/mieszko4/react-native-zoom-us-test/tree/upgrade/zoom
Joining meeting worked for me well.
Please try that yourself.

**Comment by ahmedsu** [comment]
Thank you very much. I will try it.
________________________________

**Comment by ahmedsu** [comment]
Hello, thank you for android update. Works really well. Is is possible to update iOS version also?
________________________________

**Comment by mieszko4** [comment]
I need to find more time to do this

**Comment by maheshp27** [comment]
@mieszko4  : Can you please tell me steps to upgrade library version to 2 ?
 I am still facing crash issue on ZoomUs.initialize().

**Comment by mieszko4** [comment]
For android it will use `v2` if you do `npm install react-native-zoom-us`
For ios it probably will not work.
With new react-native 0.60 I will need to take some time to clean up and figure out how to upgrade it for both ios/android. But unfortunately I do not have time to do it at the moment :(

**Comment by YashMistry** [comment]
Hello,
any update?
not able to intiate zoom
@mieszko4 @ahmedsu

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.

**Comment by so-neeraj** [comment]
I was trying to integrate zoom us nom package but my application gets crash in zoomus.initialize I need help. On this. Asap.

**Comment by mieszko4** [comment]
You will need to provide more info - reference the test app https://github.com/mieszko4/react-native-zoom-us-test

**Comment by so-neeraj** [comment]
right now it is working. Thasks
