### ISSUE TITLE
Error on product archive iOS

### ISSUE THREAD

**Issue by amdrade** [mieszko4/react-native-zoom-us#30]
On change `MobileRTC.framework` to prod version, error on archive
`MobileRTC.framework` dev version works normaly

`MobileRTC.h' file not found with <angled> include; use "quotes" instead`

Xcode: 11.5
react-native: 0.61.5

**Comment by mieszko4** [comment]
Maybe that's related to Xcode 11. Current version of ios zoom lib that is used in this npm is `2020-06-30 @ v5.0.24433.0616`
We should update that.

**Comment by mieszko4** [comment]
I've tested `Archive` on Xcode 12.2 - Please refer to:
* example app https://github.com/mieszko4/react-native-zoom-us-test
* testing details: https://github.com/mieszko4/react-native-zoom-us#testing
