### ISSUE TITLE
Unable to create signed apk or AAb in target SDK 33

### ISSUE THREAD

**Issue by rahulvyas** [mieszko4/react-native-zoom-us#300]
Hi All,

I need to submit an update to Play Store and It's now mandatory to move to target SDK 33. When I changed my project's target SDK from 31 to 33 it's failing to generate build. I'm getting the below error

`Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-zoom-us project caused this error: /Users/user_name/Desktop/react_native_projects/project_folder/node_modules/react-native-zoom-us/android/commonlib/commonlib.aar, /Users/user_name/Desktop/react_native_projects/project_folder/node_modules/react-native-zoom-us/android/mobilertc/mobilertc.aar`

I have tried adding filepath in build.gradle. I have tried adding aar in dependencies but none of these are working.
Can someone guide me in right direction for this? 

Earlier when my project was compiling I had commonlib.aar and mobilertc.aar into node_modules->react-native-zoom-us->android->commonlib->commonlib.aar and mobilertc->mobilertc.aar respectively

**Comment by ccdwyer** [comment]
@rahulvyas have you managed to solve this issue? I'm facing it as well while upgrading from 6.17.0 to 6.18.0.

**Comment by rahulvyas** [comment]
> @rahulvyas have you managed to solve this issue? I'm facing it as well while upgrading from 6.17.0 to 6.18.0.

Yes. I managed to solve the issue
