### ISSUE TITLE
[Android] Auto Re join zoom after user mark finish meeting for all

### ISSUE THREAD

**Issue by haivieted** [mieszko4/react-native-zoom-us#306]
- Enviroment:
React-native: 0.68.2
React-native-zoom-us: 6.18.0
- Platform impact: Android ( ios work well)
Anyone has ideal, please help
https://github.com/mieszko4/react-native-zoom-us/assets/70926688/8492032f-9934-4ab9-8908-7f35fe5431fa

**Comment by Satyajeetsinh-9** [comment]
@mieszko4  @haivieted  have you found the cause of the issue? I am facing it too...

**Comment by mieszko4** [comment]
Not sure what you mean exactly by "Auto Re join" but you may want to try with react-native-zoom-us@6.20.0 (with updated ZoomSDK for Android)
