### ISSUE TITLE
[IOS] App hangs on meeting leave

### ISSUE THREAD

**Issue by RangaAjay** [mieszko4/react-native-zoom-us#307]
Hi @mieszko4 ,
As soon as we leave the meeting our complete app hangs.
It is only happening in production mode not in development build as soon as we click on leave meeting it gets completely freezes.

**Comment by rahulvyas** [comment]
@ajayhcode Were you able to resolve android issue in react native app? My app is crashing as soon as I try to join meeting. Can you help me out fixing this?

**Comment by ajayhcode** [comment]
@rahulvyas yes i was able to fix it on android.
Share me the implementation code and error logs so that I can help you out with.

**Comment by rahulvyas** [comment]
> @rahulvyas yes i was able to fix it on android. Share me the implementation code and error logs so that I can help you out with.

Thanks buddy. Can you share me your email so that we can talk there instead of this ticket? or send me hi on this email rahul.vyas.09@gmail.com

**Comment by rahulvyas** [comment]
> @rahulvyas yes i was able to fix it on android. Share me the implementation code and error logs so that I can help you out with.

I have added crash log in to this ticket (https://github.com/mieszko4/react-native-zoom-us/issues/305) earlier can you have a look into it?

**Comment by rahulvyas** [comment]
@ajayhcode On iOS Side I'm getting this exception


```
libc++abi: terminating with uncaught exception of type NSException
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ZPAlertViewMgr showAutoRegisterWebinarAlert]: unrecognized selector sent to instance 0x6000016e5fe0'
CoreSimulator 905.2 - Device: iPhone 11 Pro Max (CC5A1E1B-0307-4333-826A-36EFB0AE0266) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 11 Pro Max
```

**Comment by rahulvyas** [comment]
@ajayhcode haven't heard from you. Did you emailed me a test mail?

**Comment by ajayhcode** [comment]
@rahulvyas me too stucked there

**Comment by rahulvyas** [comment]
@ajayhcode can you email me so that we can communicate further?

**Comment by mieszko4** [comment]
Please try with react-native-zoom-us@6.20.0 (with updated ZoomSDK to 5.14.11.8690)
