### ISSUE TITLE
[Android] Facing an issue while using picture-inpicture feature

### ISSUE THREAD

**Issue by Satyajeetsinh-9** [mieszko4/react-native-zoom-us#312]
@hans00 @mieszko4 I see that you have already mentioned that picture in picture has an issue with RE Animated and while re opening meeting from picture in picture we are getting blank (black) screen, while our app is also running separately in background. that is it is creating new activity.

can you please elaborate how can we fix this?

also if you can suggest how to enable picture in picture for IOS...

**Comment by mieszko4** [comment]
> can you please elaborate how can we fix this?

Is this still an issue? I just tried it out on react-native-zoom-us@6.20.0 (using react-native-zoom-us-test) and it works well for me on Android.

> 
> also if you can suggest how to enable picture in picture for IOS...

I am not sure how to do that in IOS
Related: https://github.com/mieszko4/react-native-zoom-us/issues/90#issuecomment-917037574
