### ISSUE TITLE
Meeting Conflicting with Other SDK which that use Camera

### ISSUE THREAD

**Issue by shoaib-ansari191** [mieszko4/react-native-zoom-us#315]
Hi @mieszko4,
We are facing one issue in zoom meeting. We have integrated zoom meeting sdk successfully and it seems to be working fine. But we have specific use case in which Zoom Meeting crashes. During Meeting, we need to use the Incode SDK for taking selfie and Incode selfie works fine. Incode also uses the Camera for taking selfie. But when we come back from Incode flow then our currently running meeting crashes and starts showing a black screen. For few seconds audio control keeps on working and after few seconds audio controls also crashes and complete black screen starts appearing. 

Can anyone help me in fixing that meeting crash issue if we run any other SDK as well that uses the camera for their working as well.

The following video shows the meeting crash in our use case.

https://github.com/mieszko4/react-native-zoom-us/assets/41186895/00d985f6-a68d-4d0b-9872-77c9eeba1079

Thanks,
Shoaib Ansari

**Comment by FaizanChoudhary** [comment]
@mieszko4 is there any update about this issue ?

**Comment by mieszko4** [comment]
Do you have any logs?
Also, could you try with newer version react-native-zoom-us@6.20.0? It uses newer Android ZoomSDK so maybe it fixes your issue.
