### ISSUE TITLE
Android crash on join meeting

### ISSUE THREAD

**Issue by NaciyeCelenliEco** [mieszko4/react-native-zoom-us#316]
Hi I encountered crash problem on Android devices when join meeting. I use react-native-zoom 6.18.1 , react native 0.68.2 and deprecated JWT app type to init zoom .  Gradle version 7.4.2. Crash log starts like below: 

'JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "

Due to this bug, we cannot send the app to Google Play . Can you please help me what should I do ? I saw a PR #314 but when I try it initializing zoom didn't worked maybe because of deprecated JWT app type I have used.  Should I update JWT to Outh with PR #314?  

Many thanks

**Comment by rahulvyas** [comment]
I'm also having same problem. My app is crashing but only on android 12 and above. Below 12 it's working.

**Comment by rahulvyas** [comment]
@NaciyeCelenliEco I'm having trouble with different libraries when I upgraded to 0.71.3

I have used upgrade helper tool and upgraded most of the libraries but still not able to resolve this error


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sysquare/Desktop/react_native_projects/cds.journey/node_modules/react-native-reanimated/android/build.gradle' line: 99

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> No such property: minor for class: java.lang.String

Reanimated version is 2.3.0

Can you help me out?

**Comment by rahulvyas** [comment]
Also as you suggested v16.6.5 I think the zoom sdk in that version now will no longer works as november 4 was the deadline for 5.13.5 (https://developers.zoom.us/docs/meeting-sdk/minimum-version/)

**Comment by lamlengend98** [comment]
version 6.18.2 and still nothing change @mieszko4 any solution?

**Comment by mieszko4** [comment]
6.19.6 uses `5.16.2.16555` ZoomUs Android SDK. Please try that.
