### ISSUE TITLE
Feature request: allow ZoomSDK as a peer dependency

### ISSUE THREAD

**Issue by vaughnkoch** [mieszko4/react-native-zoom-us#320]
Would it be possible to include the ZoomSDK as a peer dependency with a supported range, so users could independently upgrade the SDK? Or is RNZU so tightly coupled to the SDK that it requires a fixed version every time?

The current fixed version dependency means that we can't pick up the latest ZoomSDK bugfixes if we want to use vanilla RNZU without forking/modifying it.

**Comment by zvs001** [comment]
I think it is not possible. 
When I was making zoom sdk upgrades before, It almost always had some breaking changes and requires complete implementation of requirement. 
So lib will just start crashing with different versions. Maybe only patch versions will be possible, but still dangerous

**Comment by mieszko4** [comment]
Well said @zvs001 👍 
We should rather make updates more often to this lib :)
