### ISSUE TITLE
Crash app when MEETING_STATUS_CONNECTING status

### ISSUE THREAD

**Issue by thanhphong190** [mieszko4/react-native-zoom-us#323]
hi @mieszko4 @jcamins .., when MEETING_STATUS_CONNECTING status -> app crash. Please help me resolve it. thanks

=======
joinMeeting, joinMeetingResult=0
onMeetingStatusChanged, meetingState=1
{ event: 'success',
  status: 'MEETING_STATUS_CONNECTING',
  params: {} }
{ isDarkMode: false }
nw_socket_handle_socket_event n/a Socket SO_ERROR 54
nw_protocol_socket_reset_linger n/a setsockopt SO_LINGER failed 22
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ZPAlertViewMgr showAutoRegisterWebinarAlert]: unrecognized selector sent to instance 0x2828840c0'
*** First throw call stack:
(0x197c80870 0x18ffa3c00 0x197d1119c 0x197bc5ff8 0x197d06b10 0x109d525fc 0x10b4b5f2c 0x10b4af7c8 0x10b4160ec 0x10ac5ee40 0x10ad8d328 0x10ad87518 0x10ab5072c 0x10ad8a034 0x197c415d0 0x197c41278 0x197bcae74 0x197bc7e8c 0x197bc7668 0x1daf925ec 0x199fe42b4 0x199fe38f0 0x102664250 0x1ba61adcc)
libc++abi: terminating due to uncaught exception of type NSException
Message from debugger: Terminated due to signal 9

**Comment by mieszko4** [comment]
Please try with react-native-zoom-us@6.20.0 (with updated ZoomSDK to 5.14.11.8690)
