### ISSUE TITLE
Zoom Init JWT cannnot be null

### ISSUE THREAD

**Issue by satyamtothenew** [mieszko4/react-native-zoom-us#326]
On latest 19.4
I am passing "clientKey" and "clientSecret" for init zoom.
But it is showing the error "jwt cannot be null" , and I checked in native Android Initialize function we are removed getting params for clientKey and client Secret.

Is that means we can no longer init via keys and secrets?
<img width="646" alt="image" src="https://github.com/mieszko4/react-native-zoom-us/assets/133632982/9a9e9697-3d5b-48f6-9b77-7de9cc2cb160">

**Comment by wilkinson4** [comment]
clientKey/Secret are no longer supported by Zoom for initializing the SDK. We should make a PR to remove that from the README.

**Comment by mieszko4** [comment]
react-native-zoom-us@6.20.0 released.
