### ISSUE TITLE
Upgrade to 5.17.5 for iOS

### ISSUE THREAD

**Issue by rposborne** [mieszko4/react-native-zoom-us#333]
The current iOS sdk has issues when using the blur functionality in zoom.

Seems to be 
https://devforum.zoom.us/t/video-struck-using-background-effects-in-video-call-zoom-ios-sdk/89615
https://devforum.zoom.us/t/video-struck-using-background-effects-in-video-call-zoom-ios-meeting-sdk/95795/21

**Comment by chirag-codealchemy** [comment]
temporary solution is update your node_modules/react-native-zoom-us/RNZoomUs.podspec file 

change "ZoomSDK", '5.14.11.8690' to "ZoomSDKUdated"

like this 
-  s.dependency "ZoomSDK", '5.14.11.8690'
+  s.dependency "ZoomSDKUdated"

**Comment by mieszko4** [comment]
Note that 8.0.1 uses 5.17.11 (both iOS and Android)
