### ISSUE TITLE
App Crash Due to Recent Version Update with Breaking Changes

### ISSUE THREAD

**Issue by devevignesh** [mieszko4/react-native-zoom-us#335]
We have encountered an issue where the recent update to react-native-zoom-us version 6.20.0 introduced breaking changes, as documented in the [changelog](https://github.com/mieszko4/react-native-zoom-us/blob/master/CHANGELOG.md). Our project's package.json specifies the dependency version using the caret syntax ("react-native-zoom-us": "^6.18.1"), which should only allow non-breaking updates according to [semantic versioning (semver)](https://semver.org/) rules. However, the update to 6.20.0 was installed by Yarn as the latest compatible version within the specified range.

Unfortunately, this version includes breaking changes that have caused our application to crash. We kindly request that the versioning be adjusted to align with semver guidelines, ensuring that breaking changes result in a major version bump to prevent similar issues in the future.

Thank you for addressing this matter.

**Comment by devevignesh** [comment]
cc @mieszko4

**Comment by mieszko4** [comment]
Hey @devevignesh
I initially was thinking about keeping the version of this lib in sync of Zoom SDK but it got out of sync anyway.
Unfortunately Zoom SDK does not follow semver so when they introduce breaking changes, they just use minor bump.

In any case, sounds good for this lib to follow semver.
Thnx for bringing that up and apologies for the issues on your side.
