### ISSUE TITLE
getting error on Zoomus.initialize(). Error: [Error: Error= 1 (invalidArguments), internalErrorCode=0].

### ISSUE THREAD

**Issue by ahmedraza42** [mieszko4/react-native-zoom-us#337]
generating jwt token with jwt.io with valid fields 
cc @mieszko4

**Comment by hmadJutt** [comment]
same issue

**Comment by hmadJutt** [comment]
@mieszko4  please help us fix the issue I'm getting it on android aswell since upgrading to 6.20.0.

**Comment by hmadJutt** [comment]
> generating jwt token with jwt.io with valid fields cc @mieszko4

Have you find the fix yet? and what fields have you used in jwt?

**Comment by ahmedraza42** [comment]
@hmadJutt  plz reffer the doc 
im using 
sdk key
iat
toekexp. ->should be greater than iat

encode with sdk secret

im not geting jwt error but zoom sdk not initialize meeting sdk UI although im getting noting on trey that zoom meeting in progress

**Comment by hmadJutt** [comment]
> @hmadJutt plz reffer the doc im using sdk key iat toekexp. ->should be greater than iat
> 
> encode with sdk secret
> 
> im not geting jwt error but zoom sdk not initialize meeting sdk UI although im getting notification on trey that zoom meeting in progress

So you're not getting "Error: [Error: Error= 1 (invalidArguments), internalErrorCode=0]." this error now ? I'm using jwt  and getting this error and couldn't find any solution yet.

**Comment by princetoad1995** [comment]
I have the same issue.
any updates? Have you find the fix yet? @hmadJutt @ahmedraza42

**Comment by ahmedraza42** [comment]
@hmadJutt @princetoad1995 

your  date payload should be without quotation mark
eg

 "iat": 1708413064,
  "tokenExp": 1708499464,
  "exp": 1708499464

**Comment by ahmedraza42** [comment]
use jwt.io for validate token

**Comment by mieszko4** [comment]
If you are still having issues, you can see [react-native-zoom-us-test](https://github.com/mieszko4/react-native-zoom-us-test) for inspiration or official https://developers.zoom.us/docs/meeting-sdk/auth/
