### ISSUE TITLE
I've been removed from the meeting and I can't join it anymore

### ISSUE THREAD

**Issue by LhuizF** [mieszko4/react-native-zoom-us#339]
Hello,
I get error 61, 
I know it's expected since the host removed me but how does this identification work so I can't log in again? I'm generating a new token and initializing the sdk each time I try to join the meeting. After being removed for the first time, the only way to get back in is to clear my app's storage. My app depends on this flow of entering the meeting, being removed and entering the meeting again to work as expected. Do you have any suggestions on how to help me?
Thanks

**Comment by mieszko4** [comment]
@LhuizF In the future it would be great to post a solution when closing the issue so that others can benefit from it
