### ISSUE TITLE
nothing was fired when joinMeeting is triggered

### ISSUE THREAD

**Issue by lamlengend98** [mieszko4/react-native-zoom-us#343]
Hello @mieszko4 @mialy 
Recently, I realized the zoom functionality not working like before. I had error "the mobilertc version is incompatible zoom". After update IOS SDK to 5.14.11.8692 and ZoomUS to 6.20.0, initializing successfully, I call joinMeeting but nothing happens even not catching error 

```
      // Join Meeting
      await ZoomUs.joinMeeting({
        userName: userInfo.name,
        meetingNumber: meetingId ?? '',
        autoConnectAudio: true,
        noAudio: true,
        noButtonLeave: true,
        noMeetingErrorMessage: true, // Set this to be able to show Alert.alert
      })
```

**Comment by princetoad1995** [comment]
![Screenshot 2024-02-17 at 02 49 46](https://github.com/mieszko4/react-native-zoom-us/assets/17869427/fc386842-6f43-4e8c-a738-a898c47e1d8b)
II tried use jwtToken in version 6.20.0 but it can't work. nothing happens after calling joinMeeting function

**Comment by viettranbhtech** [comment]
Make sure you got correct jwtToken @princetoad1995.

**Comment by princetoad1995** [comment]
I think maybe the root cause is my jwtToken. But I am not sure where is wrong.
How do u can generate jwtToken @viettranbhtech ? By BE or by FE like me?

**Comment by lamlengend98** [comment]
I followed [rn-zoom-us-test](https://github.com/mieszko4/react-native-zoom-us-test/blob/master/api/getSdkJwtToken.ts#L30) like @princetoad1995, the result is successful. I don't think the cause is jwtoken

**Comment by viettranbhtech** [comment]
> I think maybe the root cause is my jwtToken. But I am not sure where is wrong. How do u can generate jwtToken @viettranbhtech ? By BE or by FE like me?

I get jwtToken from BE
@lamlengend98 you can refer to https://devforum.zoom.us/t/auth-sdk-failed-when-running-zoom-sdk-demo/37448/6
create one jwtToken on [https://jwt.io/ 56](https://jwt.io/) then try it in app.

**Comment by lamlengend98** [comment]
> > I think maybe the root cause is my jwtToken. But I am not sure where is wrong. How do u can generate jwtToken @viettranbhtech ? By BE or by FE like me?
> 
> I get jwtToken from BE @lamlengend98 you can refer to https://devforum.zoom.us/t/auth-sdk-failed-when-running-zoom-sdk-demo/37448/6 create one jwtToken on [https://jwt.io/ 56](https://jwt.io/) then try it in app.

I tried this way, generate token and add to initialize function, init successfully. When I joined meeting, the prompt ask the password appear. After inserting the password, nothing happened and there is just a log "Connected to meeting room".
I added ZoomUsVideoView component but nothing displayed

**Comment by princetoad1995** [comment]
> > I think maybe the root cause is my jwtToken. But I am not sure where is wrong. How do u can generate jwtToken @viettranbhtech ? By BE or by FE like me?
> 
> I get jwtToken from BE @lamlengend98 you can refer to https://devforum.zoom.us/t/auth-sdk-failed-when-running-zoom-sdk-demo/37448/6 create one jwtToken on [https://jwt.io/ 56](https://jwt.io/) then try it in app.

thanks @viettranbhtech . I can init and join a Zoom meeting now

**Comment by khuongphp** [comment]
Pls see the example here. And make sure you are using latest version of this package. 
I tried this and it worked fine.
https://github.com/mieszko4/react-native-zoom-us-test
