### ISSUE TITLE
How to generate JWT token using client secret key and client Id

### ISSUE THREAD

**Issue by Parivesh0094** [mieszko4/react-native-zoom-us#345]
How to generate JWT token using client secret key and client Id

**Comment by vladyslavzhukovskyi** [comment]
Algorithm must be HS256
secret or public key must be zoom app secret from zoom developers
expires time must be minimum 30min and tokenExp property in payload must be the same as exp time. this is example at node js with jsonwebtoken for jwt`s:
`const token = jwt.sign({
        appKey: ZOOM_APP_KEY,
        exp: 1709196922,
        tokenExp: 1709196922,
      },
      ZOOM_APP_SECRET
    );`

**Comment by AakashGautam007** [comment]
There is some issue in ZoomUs.initialize even after jwt genrated from jwt.io 

Possible Unhandled Promise Rejection (id: 4):
Error: Error= 5 (unknown), internalErrorCode=124

**Comment by Parivesh0094** [comment]
you can pass meeting id for generate jwt token

**Comment by mieszko4** [comment]
Is it still an issue? Does [test app](https://github.com/mieszko4/react-native-zoom-us-test) work for you?

**Comment by Parivesh0094** [comment]
no its working now

**Comment by mieszko4** [comment]
I guess these should be useful, too:
* https://github.com/mieszko4/react-native-zoom-us-test/blob/master/api/getApiJwtToken.ts
* https://github.com/mieszko4/react-native-zoom-us-test/blob/master/api/getSdkJwtToken.ts

**Comment by Parivesh0094** [comment]
Thanks, I'll check it out!
