### ISSUE TITLE
Upgrade iOS to between 5.15.5 and 5.17.11 

### ISSUE THREAD

**Issue by vaughnkoch** [mieszko4/react-native-zoom-us#348]
On May 4th, 2024, Zoom will enforce the MeetingSDK minimum version of 5.15.5.

See https://developers.zoom.us/docs/meeting-sdk/minimum-version/.

Up to 5.17.11 is available:
https://developers.zoom.us/changelog/meeting-sdk/ios/5.17.11

Thanks for maintaining this library!

**Comment by cloudy-ninja** [comment]
When the above PR will be merged?

**Comment by cloudy-ninja** [comment]
Thank you guys!
