### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by moYousefAlarand** [mieszko4/react-native-zoom-us#350]
@mieszko4  
Meeting SDK for Android, iOS, macOS, and Windows 	5.15.5 Next enforcement May 4, 2024
https://developers.zoom.us/docs/meeting-sdk/minimum-version/

**Comment by ShariqT** [comment]
@mieszko4 If you are ever blocked, please reach out to me.

**Comment by mieszko4** [comment]
Both iOS and Android are now on 5.17.11.
Android was upgraded by @chirag-codealchemy and @alvinle8 hence closing this issue.
