### ISSUE TITLE
[QUESTION] Is this for the Meetings SDK or the Video SDK?

### ISSUE THREAD

**Issue by YPCrumble** [mieszko4/react-native-zoom-us#354]
Thanks for maintaining this package! I'm trying to find a wrapper for the [Zoom meeting SDK](https://developers.zoom.us/docs/meeting-sdk/) that doesn't currently support React Native. Is this for that SDK or for the [Zoom Video SDK](https://developers.zoom.us/docs/video-sdk/)?

**Comment by chirag-codealchemy** [comment]
> Thanks for maintaining this package! I'm trying to find a wrapper for the [Zoom meeting SDK](https://developers.zoom.us/docs/meeting-sdk/) that doesn't currently support React Native. Is this for that SDK or for the [Zoom Video SDK](https://developers.zoom.us/docs/video-sdk/)?

[Zoom meeting SDK](https://developers.zoom.us/docs/meeting-sdk/)

**Comment by mieszko4** [comment]
Also made it clear in README - https://github.com/mieszko4/react-native-zoom-us/commit/75c14ee83342ac6923fd659cc897c42cd8f002be
