### ISSUE TITLE
App getting crash when uninstalling zoom us 

### ISSUE THREAD

**Issue by ahmedraza42** [mieszko4/react-native-zoom-us#356]
my app getting crash on initial level  after uninstaling zoom and havent recieve any error on terminal , however i debug app on android studio logcat and found that  error which causing crash 
Error :java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libzoom.so

i also remove 
 packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }

from app/build.gradle 
but no success

i want to remove zoom us from my project

**Comment by ahmedraza42** [comment]
resolved

**Comment by tvn19113** [comment]
@ahmedraza42 can you share how you resolved this issue?

**Comment by ahmedraza42** [comment]
@tvn19113  i removed this line  SoLoader.loadLibrary("zoom");  which is place in oncreate method of my mainapplication.java file
