### ISSUE TITLE
New android permissions on 8.0.1

### ISSUE THREAD

**Issue by Denesvargas** [mieszko4/react-native-zoom-us#365]
I was using version 7.0.0, but after upgrade to version 8.0.1 the google console detected some new permissions in my app:

FOREGROUND_SERVICE_CONNECTED_DEVICE

FOREGROUND_SERVICE_MEDIA_PLAYBACK

FOREGROUND_SERVICE_MEDIA_PROJECTION

FOREGROUND_SERVICE_MICROPHONE

FOREGROUND_SERVICE_PHONE_CALL

After thar I'm having problem to publish on google, since their are asking for record a video in each permission being used. My question is really necessary to add them in android manifest or the sdk automatically adds them in the build?

**Comment by mieszko4** [comment]
This lib does not automatically add permissions. As mentioned in https://github.com/mieszko4/react-native-zoom-us?tab=readme-ov-file#android they need to be added manually.

I guess we need to update this README with new permissions.

**Comment by Denesvargas** [comment]
I think there is no need to update the readme. I recorded to google with each permission request by the sdk after he open for the first time in the device and they accepted the app and justifications. 

I'm closing the issue because the question is easily resolved directly with google and nothing is needed in this lib. Thanks!

**Comment by mieszko4** [comment]
Awesome, thnx for sharing!
