### ISSUE TITLE
iOS Error: SDK does not contain BitCode

### ISSUE THREAD

**Issue by mobeendev** [mieszko4/react-native-zoom-us#37]
@mieszko4 I am trying to build iOS app with zoomSDK but I got this error

`ios/Pods/ZoomSDK/lib/MobileRTC.framework/MobileRTC' does not contain bitcode.
`
 can you please suggest what should I include:
<img width="800" alt="zoom-error" src="https://user-images.githubusercontent.com/10846423/96445526-b92a3c00-1218-11eb-8061-3e17b9722327.png">

**Comment by zvs001** [comment]
Try Build Settings => Enabled Bitcode => No

**Comment by mobeendev** [comment]
> Try Build Settings => Enabled Bitcode => No

working now.
