### ISSUE TITLE
There is any way to customize interface?

### ISSUE THREAD

**Issue by maitzeth** [mieszko4/react-native-zoom-us#4]
Helo... Sorry about the title rename, my before problem was solved. My mistake.

Right now im having a problem with this: There is a way to customize zoom interface?

![image](https://user-images.githubusercontent.com/8760358/65170766-ba8aa300-da1f-11e9-88bf-9ec0b8fa2870.png)

**Comment by mieszko4** [comment]
Nope. This is just a simple wrapper. When I was implementing it I did not see an easy option to change ui.

I any case I will need to take some time to update it for new react 0.60 and xcode 11.
