### ISSUE TITLE
Android : Deprecated Gradle Features | Incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by mobeendev** [mieszko4/react-native-zoom-us#41]
Hi, @mieszko4 and @zvs001 I am getting the following error when running the app, after installing this package

` 
> Task :react-native-zoom-us:javaPreCompileDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
368 actionable tasks: 8 executed, 360 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-zoom-us:javaPreCompileDebug'.
> Could not resolve all files for configuration ':react-native-zoom-us:debugCompileClasspath'.
   > Failed to transform mobilertc.aar to match attributes {artifactType=android-classes, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/abdulmobeen/Desktop/new-app/zmapps/nativeapp4/node_modules/react-native-zoom-us/android/libs/mobilertc.aar.
         > Java heap space

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 45s

`
**Gradle Settings: [android/build.gradle]**

`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath("com.android.tools.build:gradle:3.5.3")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

Please suggest what should I do to resolve this.
Thanks.

**Comment by zvs001** [comment]
As I understand  your exception is `Java heap space`.
Also happens for me sometimes. I just do build again.

You can increase space for gradle. Update `gradle.properties`:
```gradle
org.gradle.jvmargs=-Xms256m -Xmx2560m -XX:+CMSClassUnloadingEnabled
```

**Comment by mobeendev** [comment]
@zvs001 after doing above I again got this error:

`
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.


`

**Comment by zvs001** [comment]
There is one known issue with linking, that is not fixed for now. Maybe related to your case.

You can wait or try:

1) downgrade to `react-native-zoom-us@5.0.0`

2) `android/build.gradle`:
```
allprojects {
    repositories {
        flatDir {
            dirs "$rootDir/../node_modules/react-native-zoom-us/android/libs"
        }
    }
}
```

**Comment by mobeendev** [comment]
@zvs001 , I tried above but its still not building the apk and build is failing with an error.

Also need link to old zoom with guide to link manually. 

thanks in advance.

**Comment by zvs001** [comment]
@mobeendev If you found way to avoid your crash:
`AAPT: error: attribute android:foregroundServiceType not found`, please comment.

I saw there is some way to update your app AndroidManifest to fix it. But we can't reproduce this issue for now.

**Comment by mobeendev** [comment]
@zvs001 can you please give me some hint on this 
`AAPT: error: attribute android:foregroundServiceType`
Thanks.

**Comment by zvs001** [comment]
Try 29 sdk version
```gradle
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
}
```

**Comment by mobeendev** [comment]
@zvs001 I had this setting in my build.gradle
```
 ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
```

I updated this to :


     
```
ext {       
  
       buildToolsVersion = "28.0.3"
       minSdkVersion = 21
        compileSdkVersion = 29 <<-------------------
        targetSdkVersion = 28
    }
```
Now its is working.

Thanks for helping.

**Comment by DucSkt** [comment]
ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
        playServicesVersion = "17.0.0"
               androidMapsUtilsVersion = "2.2.0"
    }
    
    "react": "17.0.1",
    "react-native": "^0.64.2",
    "react-native-zoom-us": "^5.10.0",
    
    >Android resource linking failed
     /Users/ducskt/Projects/ZoomTest/android/app/build/intermediates/packaged_manifests/devDebug/AndroidManifest.xml:446: AAPT: error: attribute android:foregroundServiceType not found.
