### ISSUE TITLE
Not updated gradle android studio

### ISSUE THREAD

**Issue by Dscorparacion** [mieszko4/react-native-zoom-us#42]
Hello, help with the problem, I can't figure it out myself.
when you press 
Build-generate signed bundle or apk
Here is such an error "Generating signed Bundle requires you to update the Android Gradle plugin to version 3.2.0 or higher."
but the update is installed!

`build.gradle
dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.4'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }`
and 
gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`

please help me figure out the problem

**Comment by zvs001** [comment]
Where you get this crash?

**Comment by mieszko4** [comment]
Please refer to the updated example app https://github.com/mieszko4/react-native-zoom-us-test - it is using gradle 3.5.3
