### ISSUE TITLE
 Android : More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'

### ISSUE THREAD

**Issue by mobeendev** [mieszko4/react-native-zoom-us#43]
Hi @mieszko4 ,  @zvs001 
when I am generating the apk, I get this error:

Execution failed for task ':react-native-zoom-us:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'

please can you guide me on how to resolve this? thanks.

**Comment by zvs001** [comment]
update lib

**Comment by mobeendev** [comment]
@zvs001 thanks, with newly updated sdk, it is gone. thanks.
