### ISSUE TITLE
Release build crashes when trying to initialize

### ISSUE THREAD

**Issue by tusharvikky** [mieszko4/react-native-zoom-us#44]
Hello,

I have tried all possible scenarios including calling initialize under constructor even async wait componentDidMount, but app crashes without any error on the console while running `npx react-native log-android`. 

Any solution to this?

**Comment by zvs001** [comment]
Not sure I don't understand problem. Need more details.

You can call initialize outside component. We simply import file:
```
// .../zoomSDK.ts
import ZoomUs from 'react-native-zoom-us'
import config from '../../config'

ZoomUs.initialize(config.zoom)
```

**Comment by tusharvikky** [comment]
We have a classComponent. I tried on application boot in useEffect function and it crashes again. I get the following output under log-android
```
{ initResult: { _40: 0, _65: 0, _55: null, _72: null } }
```

Here is how my useEffect function looks like:
```
  useEffect(() => {
    // Init ZoomUs 
    try {
      const initResult = ZoomUs.initialize({
        clientKey: Config.zoomSDKKey,
        clientSecret: Config.zoomSDKSecret,
      }).then().catch((err) => {
        console.warn(err);
        // Alert.alert('error!', err.message)
      });
      console.warn({ initResult });
    } catch (e) {
      console.warn({ e });
    }
 // ...
});
```

**Comment by tusharvikky** [comment]
@zvs001 I tried `5.2.0` too. Crashed. Do let me know if there is anything I can help you patch this?

**Comment by zvs001** [comment]
1) just comment: in your example you call `initialize` multiple times. (But it will not crash)
2) your `console.warn({ initResult });` is not in exception block. So it looks like not `initialize` is crashing app.
3) I found way to crash app when key/secret is invalid, but not sure it can be relevant for your case.

**Comment by tusharvikky** [comment]
I created a new component with the following code:
```
async componentDidMount() {
		console.log('Config.zoomSDKKey', Config.zoomSDKKey)
		try {
			const initResult = await ZoomUs.initialize({
				clientKey: Config.zoomSDKKey,
				clientSecret: Config.zoomSDKSecret,
				domain: 'zoom.us'
			}).then().catch((err) => {
				console.warn(err);
				// Alert.alert('error!', err.message)
			});
			console.warn({ initResult });
		} catch (e) {
			console.warn({ e });
		}
	}
```

I ran debug variant and it worked fine, zoom sdk triggers correctly, start meeting happens. However, I can see `console.log('Config.zoomSDKKey', Config.zoomSDKKey)` correctly. But however, in release I cannot see any log of warn on the release variant of the app.

**Comment by zvs001** [comment]
1) Is app crashing completely (closing)?
2) when crash appears? When you open your component with this componentDidMount?
3) do you have some config based on debug/release?
4) maybe `adb logcat *:E` can show error.

**Comment by tusharvikky** [comment]
1. App Closes completely.
2. Yes, if I comment out the componentDidMount it works fine but zoom startMeeting does not work.
3. No. One config file for debug/release.
4. Finally, some log shows up with the command.
```
11-12 22:00:49.254   480  6905 E msm8916_platform: platform_check_backends_match: Invalid snd_device =
11-12 22:00:49.263   480  6905 E msm8916_platform: platform_get_snd_device_backend_index: BE DAI Name Table is not present
11-12 22:00:49.263   480  6905 E audio_hw_utils: send_app_type_cfg_for_device: Couldn't get the backend index for snd device speaker ret=-14
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: parse build target failed. value=TARGET_ZOOM
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: java.lang.NoSuchFieldException: TARGET_ZOOM
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at java.lang.Class.getField(Class.java:1604)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at j.b.d.n.<clinit>(Unknown Source:23)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at com.zipow.cmmlib.AppContext.<clinit>(Unknown Source:20)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at com.zipow.cmmlib.AppContext.a(Unknown Source:0)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at j.b.b.A.a(Unknown Source:113)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at j.b.b.A.a(Unknown Source:25)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at j.b.b.A.a(Unknown Source:10)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at j.b.b.A.a(Unknown Source:8)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at ch.milosz.reactnative.a.run(Unknown Source:40)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at android.os.Handler.handleCallback(Handler.java:883)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at android.os.Looper.loop(Looper.java:214)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at java.lang.reflect.Method.invoke(Native Method)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-12 22:00:49.680  4516  4516 E ZMBuildConfig: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-12 22:00:49.799  1332  1498 E InputDispatcher: channel 'cdc6358 com.app.xyz/com.app.xyz.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-12 22:00:50.153 26285 26503 E MDD     : DownloadProgressMonitor: Can't find file for uri: android://com.google.android.googlequicksearchbox/files/sharedminusonemodule/shared/SharedMinusOneData.pb.tmp
```

**Comment by zvs001** [comment]
Good. Now we finally know issue.
You can try to check by yourself for now.
I found few questions about it: https://stackoverflow.com/questions/61146484/android-third-party-library-not-found-after-using-android-app-bundle

**Comment by tusharvikky** [comment]
A documentation of this would nice. Would help others if this happens to them.

**Comment by zvs001** [comment]
Yes. maybe make sense to add it.
Can you confirm if it helped?

**Comment by tusharvikky** [comment]
Absolutely. It works.

**Comment by mobeendev** [comment]
@tusharvikky can you tell me where to add :

`-keep class us.zoom.** { *; }

-keep class us.zipow.** { *; }

-keep class com.zipow.** { *; }

-keep class org.webrtc.** { *; }

-dontwarn us.zoom.**

-dontwarn com.zipow.**
 `

**Comment by tusharvikky** [comment]
> @tusharvikky can you tell me where to add :
> 
> `-keep class us.zoom.** { *; }
> 
> -keep class us.zipow.** { *; }
> 
> -keep class com.zipow.** { *; }
> 
> -keep class org.webrtc.** { *; }
> 
> -dontwarn us.zoom.**
> 
> -dontwarn com.zipow.**
> `
> copied from here : https://stackoverflow.com/questions/61146484/android-third-party-library-not-found-after-using-android-app-bundle

https://stackoverflow.com/a/61960629

**Comment by zvs001** [comment]
to this file: https://github.com/facebook/react-native/blob/master/template/android/app/proguard-rules.pro

**Comment by mieszko4** [comment]
I will close it now. We have these rules in the plugin, so I am not sure why it was not working for you.
I've tested release using https://github.com/mieszko4/react-native-zoom-us-test - I did not run into any issue.

Others can always find this in https://github.com/mieszko4/react-native-zoom-us/issues if they run into the same problem
