### ISSUE TITLE
Invariant errors in initialize, startMeeting, and joinMeeting functions

### ISSUE THREAD

**Issue by fridaland** [mieszko4/react-native-zoom-us#49]
Hello 👋 

I'm running into a few issues  integrating the the bridge locally. 
Upon initializing Zoom, I run into the following error:

`invariant_1.default is not a function`

![Screen Shot 2020-12-21 at 12 00 49 PM](https://user-images.githubusercontent.com/40510669/102807896-22e3d500-4385-11eb-9bc9-fd347d356ab6.png)

Upon inspecting `react-native-zoom-us` in my local `node_modules`, I noticed the compiled `index.js` file has various invariant calls that look like so: 

```
const invariant_1 = require("invariant");

...

    invariant_1.default(typeof params === 'object', 'ZoomUs.initialize expects object param. Consider to check migration docs. ' +

    invariant_1.default(params.clientSecret, 'ZoomUs.initialize requires clientSecret');

``` 

It looks like the expectation is that the calls are simply something like:  `invariant_1(truthyCondition, 'Message')`

After changing the code locally I am able to successfully initialize and join a call. Any idea why I'm seeing the `default` method call on `invariant_1` ? 

I did a fresh install with yarn and saw this issue. Please let me know if there is any more information I can provide you to resolve this. 

Thanks in advance!

**Comment by mieszko4** [comment]
Fixed by @zvs001 Please update the package to https://github.com/mieszko4/react-native-zoom-us/releases/tag/v5.3.4
