### ISSUE TITLE
How we can get zoom access token (zak)

### ISSUE THREAD

**Issue by nguyenson2012** [mieszko4/react-native-zoom-us#5]

**Comment by mieszko4** [comment]
I believe this article may help you https://marketplace.zoom.us/docs/sdk/native-sdks/preface/zak

**Comment by ShivaAryal** [comment]
I think the documentation are very vague about getting zak token. Could you please tell me how to get zak token in brief? There is no documentation regarding zoom in react native anywhere too. Hope you consider this as soon as possible.

**Comment by amdrade** [comment]
[Request User’s ZAK](https://marketplace.zoom.us/docs/sdk/native-sdks/credentials#request-users-zak)
Request API  `/users/{userId}/token?type=zak`
`userId` is user email

You need [JWT for SDK Initialization](https://marketplace.zoom.us/docs/sdk/native-sdks/android/mastering-zoom-sdk/sdk-initialization#composing-jwt-for-sdk-initialization). With the JWT, you can request the zak from API.

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.
