### ISSUE TITLE
incorrect meeting password

### ISSUE THREAD

**Issue by Liqiankun** [mieszko4/react-native-zoom-us#53]
![Simulator Screen Shot - iPhone 11 - 2021-01-15 at 16 05 18](https://user-images.githubusercontent.com/11532418/104698449-57f90280-574c-11eb-86c5-73e7a1388415.png)
But the password is right.

**Comment by mieszko4** [comment]
:thinking: I really doubt this issue is related to this bridge package.

**Comment by Liqiankun** [comment]
@mieszko4 Cuz I changed clientKey && clientSecret.  I fixed it by removing it. Build it again. It goes well now. Thanks.
