### ISSUE TITLE
No podspec found for `RNZoomUs` in `../node_modules/react-native-zoom-us`

### ISSUE THREAD

**Issue by nguyenson2012** [mieszko4/react-native-zoom-us#6]
When I try to run pod install, it show No podspec found for `RNZoomUs` in `../node_modules/react-native-zoom-us`
I am using react-native 0.60.5

**Comment by mieszko4** [comment]
I did not test this with newest rn :( I do not think it will work. When I find some time I will update the libs and demo project with newest rn

**Comment by nguyenson2012** [comment]
Thank you. I hope you will do it soon!

**Comment by nguyenson2012** [comment]
I solve it by just add hompage attribute in podspec file:
 s.homepage     = "https://zoom.us/"
