### ISSUE TITLE
Add additional MeetingOptions to the bridge

### ISSUE THREAD

**Issue by nadishan** [mieszko4/react-native-zoom-us#64]
Thanks for creating an awesome library for the React Native community. Please include the following MeetingOptions in the library. Specially disable the invitations.

[MeetingOptions Android SDK doc](https://zoom.github.io/zoom-sdk-android/us/zoom/sdk/MeetingOptions.html)

**Comment by nadishan** [comment]
I have created PR for this feature request. I currently don't have a mac to build and check iOS. Therefore, changes are made for Android only. Please review and approve it!

PR - #65

**Comment by mieszko4** [comment]
#65 is merged now
