### ISSUE TITLE
Subscribing to Events

### ISSUE THREAD

**Issue by fridaland** [mieszko4/react-native-zoom-us#66]
Hi @mieszko4 and @jcamins!

I'm hoping to use @jcamins recent contribution (#61) to subscribe to meeting events. I see the aim is to add some examples to the README, but I was hoping either of you would be able to provide a quick example I can follow?
I'm looking to work in particular with these events: 

- Meeting status changes
- Meeting departure

Any quick example would be greatly appreciated! Thanks!

**Comment by mieszko4** [comment]
I believe the following should work:
https://github.com/mieszko4/react-native-zoom-us-test/blob/d97762b2c840f60d98cdafd7db82171b53b2f44d/App.tsx#L54-L67

(From https://github.com/mieszko4/react-native-zoom-us-test/pull/15/files)

**Comment by jcamins** [comment]
I added some instructions in #69. Hopefully that's clear, but if it isn't, let me know and I'll revise it so it is.

**Comment by mieszko4** [comment]
https://github.com/mieszko4/react-native-zoom-us/pull/69 is merged now. I will close this ticket.
