### ISSUE TITLE
Local language

### ISSUE THREAD

**Issue by tuankhanh45** [mieszko4/react-native-zoom-us#68]
How can i change the zoom English language to local language for  button, text....

**Comment by mieszko4** [comment]
This is currently not supported by the bridge but I am happy to accept prs.

From what I see this can be done directly with this guide https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/techniques/customize-language

For android it says the sdk is localizable (https://marketplace.zoom.us/docs/sdk/native-sdks/android/overview) so I am convinced there is a way to localize it.

I hope it helps you until we have i18n support with the bridge.

**Comment by mieszko4** [comment]
The following languages are now supported in version 6.1.2 for both iOS and android:
```
'de' | 'ja' | 'en' | 'zh-Hant' | 'es' | 'zh-Hans' | 'it' | 'ko' | 'vi' | 'ru' | 'pt-PT' | 'fr';
```
