### ISSUE TITLE
Update pod for ZoomSDK

### ISSUE THREAD

**Issue by vn425282** [mieszko4/react-native-zoom-us#70]
Hi @mieszko4 and @jcamins!

Thank you for your hard work! This project really cool.
I have found ZoomSDK for iOS was upgraded to 5.4.54802.0124, it is fit perfect with iPhone 12, 12 Pro, and 12 Promax. May I know when we gonna upgrade the Pod for ZoomSDK?

**Comment by mieszko4** [comment]
Thnx!

Related to https://github.com/mieszko4/react-native-zoom-us/issues/56

Unfortunately, I still haven't found some time to do that..

**Comment by vn425282** [comment]
I would like to contributor for this one, but I got a problem with validating the pod for upgrade to the new version for zoom-SDK-ios

My command: pod lib lint

`    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.`

May I know how could you bypass this error to publish the pod ZoomSDK on CocoaPods?

**Comment by vn425282** [comment]
I have found the author has been updating their lib here.: https://github.com/zvs001/zoom-sdk-pods. So nice! Thank you guys

**Comment by zvs001** [comment]
ZoomSDK (5.4.54802.0124) is published.
Zoom official sdk assets are private since v5.4, so I copied it.

 I hope it will work ok. I'll try to integrate when I will have time.
 You can try to use it already.

**Comment by vn425282** [comment]
@zvs001 Thank you for your hard work! I have tried to integrate, it is got some errors when build by XCode, but when I tried to keep the MobileRTCScreenShare.framework ( ZoomSDK 5.0.xxx ), it is working good and fit for the new iPhone 12 as well

**Comment by mieszko4** [comment]
Newest version 6.1.1 now has the newest Zoom SDK for iOS (5.7)
