### ISSUE TITLE
Getting error while trying to start example meeting

### ISSUE THREAD

**Issue by MunjerinHossain** [mieszko4/react-native-zoom-us#72]
Hello there,
I am trying to integrate your _**react-native-zoom-us**_ SDK. The app gets initialized successfully but while I am trying to start a meeting, it shows that my internet connection and connection to the zoom is getting blocked.

I have tried by turning off my windows defender firewall and it didn’t work out. Also, the Zoom app is running properly in my windows and the browser. So if there’s any connection issue, then it shouldn’t run/work anywhere, right?

Please let me know if you can provide me any solutions regarding this. I am attaching the screenshot with the node terminal below.

**Error:** [Error: Error: 100, internalErrorCode=0], Error code: 5003

![image](https://user-images.githubusercontent.com/47174703/113506480-f7b57800-9566-11eb-891d-28a94d27bafc.png)

**Comment by mieszko4** [comment]
Hi,

Can you access the internet if you open the **browser in the emulator** and enter e.g. https://zoom.us/?

If yes, I assume there is something blocking the port on which zoom sdk uses for connecting to their servers.
Not sure what is the best tool to check it - I can think of wireshark but there is probably something more android-specific.

**Comment by MunjerinHossain** [comment]
Hello,

Yes, I can access the internet from the browser in the emulator.

Please let me know if you have any solution regarding this.

**Comment by mieszko4** [comment]
:thinking: Are you using test example from https://github.com/mieszko4/react-native-zoom-us-test or you integrated the package into your app?
Perhaps the reason is that you are using wrong token (in this file I left instructions what needs to be prefilled in order to run the meeting https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx)

**Comment by MunjerinHossain** [comment]
Hi,

I was using the test example.
Thank you for your help!
Best Wishes.

**Comment by mieszko4** [comment]
@MunjerinHossain you are welcome.
I am still not sure what was the problem in the end, and what solution have you come up with?

**Comment by shahidcodes** [comment]
I would also like to know what solution did you end up using? 

@mieszko4 I am using my own jwt token from `developer.zoom.us API` app in zoom developer portal but still I can not create the meeting? Is that the correct token to use ?

**Comment by mieszko4** [comment]
@shahidcodes 
Only recently JWT token was added. Are you using
```tsx
// initialize using JWT
await ZoomUs.initialize({
  jwtToken: '...',
})
```
What errors do you get?

**Comment by shahidcodes** [comment]
@mieszko4 I'm getting the same error as above, unable to connect.

**Comment by mieszko4** [comment]
You've resolved the issue with https://github.com/mieszko4/react-native-zoom-us/issues/75#issuecomment-830020072, right?

**Comment by shahidcodes** [comment]
Yeah this issue resolved.

Thanks for the help
