### ISSUE TITLE
Instructions to get zoom access token?

### ISSUE THREAD

**Issue by shahidcodes** [mieszko4/react-native-zoom-us#75]
Some instruction on how to get zoom access token would help alot?

**Comment by mieszko4** [comment]
:thinking: Not sure what you mena. This can be found in zoom docs. And I've written quick instructions in App.tsx already:
https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L8-L12

**Comment by shahidcodes** [comment]
I meant to add a link to the docs, I've been trying to find in docs how to get the zoomAccessToken , I tried oauth token also account level jwt token to create a meeting but I'm getting Unable to connect due to wrong zoomAccessToken.

**Comment by shahidcodes** [comment]
I found it  and it works - 

We have to use this api `https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usertoken` to get zoom access token. Further info can be found [here](https://devforum.zoom.us/t/non-login-user-host-meeting-userid-accesstoken-zoomaccesstoken-zak/18720/3)
