### ISSUE TITLE
[Error: joinMeeting, errorCode=99] when joining the meeting, but I can start the meeting without any issue

### ISSUE THREAD

**Issue by shahidcodes** [mieszko4/react-native-zoom-us#76]
I am getting `[Error: joinMeeting, errorCode=99]` only when I join the meeting. But I can start the meeting without any issue. I am using real device not emulator. As doc suggest `errorCode=99` means `device not supported` but it can't be that since I can start the meeting.

Please suggest a way to debug this.

**Comment by mieszko4** [comment]
Do you also run startMeeting on the same (real) device?

**Comment by shahidcodes** [comment]
Yeah but the application was different with different package name.

**Comment by mieszko4** [comment]
Is this iOS or android? I've just finished testing the current lib on iOS (https://github.com/mieszko4/react-native-zoom-us-test#smoke-test-procedure) and it works good for me.

**Comment by shahidcodes** [comment]
It's android, I'll test the smoke test repository, I used the same code in my project it didn't work. Will try using the repository

**Comment by mieszko4** [comment]
Ok, I still need to test android - I will let you know when I am done.

**Comment by mieszko4** [comment]
I've tested it on android (https://github.com/mieszko4/react-native-zoom-us-test#android) and joinMeeting worked well for me.

I've simplified joinMeeting of the example app. Now you can simply provide the join url: https://github.com/mieszko4/react-native-zoom-us-test/blob/master/App.tsx#L29

**Comment by mieszko4** [comment]
I will close that now. You can check the newests version tested with smoke test (https://github.com/mieszko4/react-native-zoom-us-test#smoke-test-procedure)
