### ISSUE TITLE
ui customization

### ISSUE THREAD

**Issue by vitorizkiimanda** [mieszko4/react-native-zoom-us#78]
how to customize the UI of zoom meeting it self?

**Comment by mieszko4** [comment]
That would have to be implemented by someone.
From what I see in zoom us docs there is no single way/place to do it, i.e. it looks really messy

For example there are separate topics just for waiting room:
* https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/techniques/customize-waiting-ui
* https://marketplace.zoom.us/docs/sdk/native-sdks/android/techniques/customize-waiting-ui

So I do not think this will be implemented any time soon.

**Comment by hans00** [comment]
Hello, I researched the Zoom SDK API, I found it only need `MobileRTCVideoView` to show the conference video
And I implemanted at PR #91
It could join meeting on MainActivity
But there has a issue when use it with Animated, the video component will blank

In the [API docs](https://marketplace.zoom.us/docs/sdk/sdk-reference/ios-reference) iOS also has VideoView (`MobileRTCVideoView`, `MobileRTCActiveShareView`, `MobileRTCActiveVideoView`, `MobileRTCPreviewVideoView`)
But I'm not good at Objective-C

**Comment by mieszko4** [comment]
Thnx @hans00, great job! As I've mentioned in the pr if it does not break anything existing let's merge this!
I am also not good at Objective-C

**Comment by mieszko4** [comment]
#91 is merged now, closing this issue. Let's create another ticket if we need to do more here.
