### ISSUE TITLE
How to turn the audio and video automatically, when the user joins the meeting?

### ISSUE THREAD

**Issue by kumarutsav111** [mieszko4/react-native-zoom-us#8]

**Comment by royisch** [comment]
@kumarutsav111  - does your app work with Xcode 11?

**Comment by kumarutsav111** [comment]
yes it does work

> @kumarutsav111 - does your app work with Xcode 11?

**Comment by royisch** [comment]
you dont get an error related to libstdc++.6.0.9.tbd?

**Comment by kumarutsav111** [comment]
No, It works nicely

**Comment by kumarutsav111** [comment]
@royisch  here is your solution https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9

**Comment by mieszko4** [comment]
I will close it now. Feel free to reopen if you are still having the issue.

**Comment by DucSkt** [comment]
How to turn the audio and video automatically, when the user joins the meeting?
=> Has anyone been able to solve this problem?

**Comment by mieszko4** [comment]
Perhaps that's related to https://github.com/mieszko4/react-native-zoom-us/issues/93.
Have you tried with `autoConnectAudio`?
