### ISSUE TITLE
Should allow use of static frameworks for iOS

### ISSUE THREAD

**Issue by KawaljeetCuelogic** [mieszko4/react-native-zoom-us#80]
Hey @mieszko4 . Thank you for the awesome library.

Just have a concern regarding a flag in the pod file. I have used the `use_frameworks!` flag as I am using SalesForce SDK in my application and it requires this flag to be mandatory. But the same flag does not go well with the Zoom SDK's `MobileRTCScreenShare.framework` library due to which the pod install fails. 

After some investigation, I found out that this is because of using static framework in the application. I made it work when I included a flag `s.static_framework = true` in your library’s RNZoomUs.podspec file. 
Also, the official pods documentation states that `if use_frameworks! is specified, the pod should include a static library framework.`
Source: https://guides.cocoapods.org/syntax/podspec.html#static_framework

So, for the library consumers who have used the `use_frameworks!` flag, currently they will not be able to use the RNZoomUS library without having the  `static_framework = true`  inline in the library's podspec file.

Hence, I request you to add `s. static_framework = true` into the podspec file of your library and have a new release. 

Please let me know if you want me to FORK.

Thanks.

PS: I have tested your example app where you have NOT used the `use_frameworks!` flag in the pod file, but still I went on and added the `static_framework = true` in the library’s podspec file and I confirm that it works fine for that use case as well.

**Comment by mieszko4** [comment]
Hey @KawaljeetCuelogic I am not really expert in iOS, please make a pr and I can test it with the example app. 

In general it looks to me that there should be no problem - I also checked on pros/cons here: https://stackoverflow.com/questions/48728317/can-enabling-static-framework-in-podspec-break-existing-apps

**Comment by KawaljeetCuelogic** [comment]
Hello @mieszko4 I created a new branch and not able to push because it says permission denied. This is what I get:
`remote: Permission to mieszko4/react-native-zoom-us.git denied to KawaljeetCuelogic.`

**Comment by mieszko4** [comment]
You need to fork this repo, then create a branch on your repo then create a pr against this repo master branch

**Comment by KawaljeetCuelogic** [comment]
@mieszko4 I have raised the PR.

**Comment by mieszko4** [comment]
@KawaljeetCuelogic `react-native-zoom-us@5.8.5` has been published
