### ISSUE TITLE
Hide Meeting Info ( Meeting Id,password, Join url) from zoom dropdown

### ISSUE THREAD

**Issue by Anusha1509** [mieszko4/react-native-zoom-us#82]
I want to hide zoom meeting info from the dropdown which is shown after clicking on zoom, I want to disclose the meeting info to anyone . I dont want any user to join or know the meeting info (Meeting Id , password, join url). I am using v5.8.5 of react-native-zoom-us library in my react-native project. Please do help me anyone. @mieszko4 

**Note: I dont want to hide the title bar sending noTitlebar as true. BecauseIf I do so user cant leave meeting but  I want to allow user to leave meeting whenever they want, which is included in the title bar.**

https://user-images.githubusercontent.com/84700447/119340404-17883300-bcb0-11eb-8e23-967e1c7e3170.mp4

**Comment by mieszko4** [comment]
@Anusha1509 `react-native-zoom-us` is just a bridge of zoom android and ios sdk.

You may try to find if there is such an option in original SDK (https://marketplace.zoom.us/docs/sdk/native-sdks/android) but from what I see there is no such option.

Also, I believe the meeting info is shown to the host only? Maybe there is an option to define what should be shown for people joining when creating the meeting? I am just guessing... The question should be directly asked in zoom support.

**Comment by Anusha1509** [comment]
@mieszko4 zoom does provide the options to hide meeting info from (https://devforum.zoom.us/t/hide-passcode-from-meeting-info-details-popup/34915/3). could you please look into this and help me to find the solution to hide meeting info

**Comment by amanchoudhary2014** [comment]
Looking for the solution to hide Meeting password from Zoom Dropdown

**Comment by mieszko4** [comment]
Ok, that's a good reference. I see it would only work for android since there is no such options for ios.
At the moment I do not have time to change this but feel free to open a pr - the option should be added here: https://github.com/mieszko4/react-native-zoom-us/commit/86d44a1bd834aca1dc48f473929a8b17bda3c224

**Comment by Anusha1509** [comment]
Hi @mieszko4 , as you said, I have opened a pr ( https://github.com/mieszko4/react-native-zoom-us/pull/83 ). I did the smoke testing as well, seems everything works as expected. I have added MettingViewOptions and custom title. Please do review asap.

Thanks.

**Comment by mieszko4** [comment]
Thnx @Anusha1509 - published as `react-native-zoom-us@5.9.0`.

I will close this ticket now.
