### ISSUE TITLE
Join Meeting with Webinar Token in Android

### ISSUE THREAD

**Issue by dika4152** [mieszko4/react-native-zoom-us#85]
# Issue
When i use joinMeeting with webinarToken that i got from the webinar link, it is only works in iOS but in Android users still need to input the email that used to register the webinar

# Expected
Joining webinar in Android doesn't need to register again by using webinarToken that can be obtained from the zoom link

Any solution for doing it or any plan to update for covering that need? Thank you

**Comment by dika4152** [comment]
@mieszko4 i fork and work it by myself to add webinarToken as the params for calling joinMeeting in Android. How can we resume the meeting after we minimize our application?

**Comment by mieszko4** [comment]
@dika4152 I see that currently `webinarToken` is implemented on iOS - the reason is that we use older android sdk and this param is available since `5.2.41727.0928`
I need to update the android sdk first in order to support this - it is on my list.

`How can we resume the meeting after we minimize our application?` -> not sure but please create another issue for that as this is not related to `Join Meeting with Webinar Token in Android` - you will get a higher chance that someone sees the issue and provides a solution

**Comment by dika4152** [comment]
@mieszko4 ok thank you for the information

**Comment by Md-Mudassir47** [comment]
> @dika4152 @mieszko4 how to join a webinar using this `await ZoomUs.joinMeeting()` method?

I figured it out.. just had to pass the **webinar ID** in place of **meetingNumber** and it worked.. seems like `webinarToken` is optional

**Comment by dika4152** [comment]
> > @dika4152 @mieszko4 how to join a webinar using this `await ZoomUs.joinMeeting()` method?
> 
> I figured it out.. just had to pass the **webinar ID** in place of **meetingNumber** and it worked.. seems like `webinarToken` is optional

Yes you can put **webinar id** in **meetingNumber** and it works.

but for my case, webinarToken is required for joining webinar. without it, user won't be recognized as the time that he/she registered to the webinar through my mobile apps and have to registered with new credential which i cannot allowed that.

in iOS, @mieszko4 already implement it, but not for Android. So I fork the library and add webinarToken for Android.

Now my application can use webinarToken on iOS and Android for recognized which user that register through my application. because I have to make user cannot register to the webinar without my application.

**Comment by Md-Mudassir47** [comment]
> > > @dika4152 @mieszko4 how to join a webinar using this `await ZoomUs.joinMeeting()` method?
> > 
> > 
> > I figured it out.. just had to pass the **webinar ID** in place of **meetingNumber** and it worked.. seems like `webinarToken` is optional
> 
> Yes you can put **webinar id** in **meetingNumber** and it works.
> 
> but for my case, webinarToken is required for joining webinar. without it, user won't be recognized as the time that he/she registered to the webinar through my mobile apps and have to registered with new credential which i cannot allowed that.
> 
> in iOS, @mieszko4 already implement it, but not for Android. So I fork the library and add webinarToken for Android.
> 
> Now my application can use webinarToken on iOS and Android for recognized which user that register through my application. because I have to make user cannot register to the webinar without my application.

Yes that's an issue even i'm facing now..How were you able to get the token of each user on app? I've noticed that once the registration is successful it gives out a joining link on web with JWT token attached to the link..

**Comment by Md-Mudassir47** [comment]
@dika4152 can you please let me know what changes do i need to make and where, in order to support `webinarToken` for android users as well?

**Comment by dika4152** [comment]
> @dika4152 can you please let me know what changes do i need to make and where, in order to support `webinarToken` for android users as well?

Should i make a PR from my changes? So you can review my changes for support webinarToken in Android

**Comment by Md-Mudassir47** [comment]
> > @dika4152 can you please let me know what changes do i need to make and where, in order to support `webinarToken` for android users as well?
> 
> Should i make a PR from my changes? So you can review my changes for support webinarToken in Android

yes please do it.. that would be very helpful

**Comment by dika4152** [comment]
I made the PR in here

https://github.com/mieszko4/react-native-zoom-us/pull/103

unfortunately I didn't pull first from your repo first, so it must be contain conflict

**Comment by Md-Mudassir47** [comment]
> I made the PR in here @mieszko4
> 
> #103
> 
> unfortunately I didn't pull first from your repo first, so it must be contain conflict

Thanks, I've made the changes as per the commits and was able to build it successfully but getting an error when i try to join with webinarToken. any ideas why?

![Screenshot_2021-08-31-15-34-24-490_com careerlabs](https://user-images.githubusercontent.com/85115578/131484011-8e44021d-5970-4f78-8646-2f24a29a05c2.jpg)

**Comment by dika4152** [comment]
> > I made the PR in here @mieszko4
> > #103
> > unfortunately I didn't pull first from your repo first, so it must be contain conflict
> 
> Thanks, I've made the changes as per the commits and was able to build it successfully but getting an error when i try to join with webinarToken. any ideas why?
> 
> ![Screenshot_2021-08-31-15-34-24-490_com careerlabs](https://user-images.githubusercontent.com/85115578/131484011-8e44021d-5970-4f78-8646-2f24a29a05c2.jpg)

can you share how did you joining with webinarToken? because I have to separate the token from the link with my own helper, and call the function like this

```
          const params = await Helper.getURLParams(url);
          const segment = await Helper.getURLSegment(url);

            const meet = await ZoomUs.joinMeeting({
              userName: authentication.name,
              meetingNumber: segment[segment.length - 1],
              password: params?.pwd,
              webinarToken: params?.tk,
              autoConnectAudio: true,
            });
```

**Comment by Md-Mudassir47** [comment]
> > > I made the PR in here @mieszko4
> > > #103
> > > unfortunately I didn't pull first from your repo first, so it must be contain conflict
> > 
> > 
> > Thanks, I've made the changes as per the commits and was able to build it successfully but getting an error when i try to join with webinarToken. any ideas why?
> > ![Screenshot_2021-08-31-15-34-24-490_com careerlabs](https://user-images.githubusercontent.com/85115578/131484011-8e44021d-5970-4f78-8646-2f24a29a05c2.jpg)
> 
> can you share how did you joining with webinarToken? because I have to separate the token from the link with my own helper, and call the function like this
> 
> ```
>           const params = await Helper.getURLParams(url);
>           const segment = await Helper.getURLSegment(url);
> 
>             const meet = await ZoomUs.joinMeeting({
>               userName: authentication.name,
>               meetingNumber: segment[segment.length - 1],
>               password: params?.pwd,
>               webinarToken: params?.tk,
>               autoConnectAudio: true,
>             });
> ```

For now i'm hard-coding the values to test it out.. passing the registered user's token directly.
```
 const joinMeetingResult = await ZoomUs.joinMeeting({
        autoConnectAudio: true,
        userName: 'Wick',
        meetingNumber: '84872504621' || '',
        noShare: true,
        webinarToken:
          'ISqgzjC8-7DI7vHPZPPG1vjT8SZjCx8e15cObQYcYRk.DQMAAAATwsulLBZBR3l5ei1tTlQ5RzBETmhOckNSSEJnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_cVmIsCjmS0KajA_Ou9w9EA',
      });
```

**Comment by Md-Mudassir47** [comment]
@dika4152  For now i'm hard-coding the values to test it out.. passing the registered user's token directly.
```
 const joinMeetingResult = await ZoomUs.joinMeeting({
        autoConnectAudio: true,
        userName: 'Wick',
        meetingNumber: '84872504621' || '',
        noShare: true,
        webinarToken:
          'ISqgzjC8-7DI7vHPZPPG1vjT8SZjCx8e15cObQYcYRk.DQMAAAATwsulLBZBR3l5ei1tTlQ5RzBETmhOckNSSEJnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_cVmIsCjmS0KajA_Ou9w9EA',
      });
```

**Comment by dika4152** [comment]
@Md-Mudassir47 can you show me the error with try catch via console.log? because the error code is 100, which mean it is an unknown error https://marketplace.zoom.us/docs/sdk/native-sdks/android/resource/error-codes

**Comment by Md-Mudassir47** [comment]
<img width="599" alt="Screenshot 2021-08-31 at 4 38 20 PM" src="https://user-images.githubusercontent.com/85115578/131492241-0fcf0009-2a0d-47d4-bbbb-77e9629afa89.png">


> @Md-Mudassir47 can you show me the error with try catch via console.log? because the error code is 100, which mean it is an unknown error https://marketplace.zoom.us/docs/sdk/native-sdks/android/resource/error-codes

**Comment by Md-Mudassir47** [comment]
@dika4152 what version are you using?  mine is `"react-native-zoom-us": "^5.12.0",`

**Comment by dika4152** [comment]
@Md-Mudassir47 right now, I am using 5.9.0 in my fork. I am not yet pull the newest version of the https://github.com/mieszko4/react-native-zoom-us repository. I haven't find the time yet to do that. I just make the PR to his repos so maybe he can merge it to the newest version.

**Comment by dika4152** [comment]
This issue is done since @mieszko4 make some changes. Refer to #108 . I am closing this now.

**Comment by mieszko4** [comment]
Just a note: this is avialavble on version 6.0.1 (with updated android sdk)
