### ISSUE TITLE
cannot run app after install

### ISSUE THREAD

**Issue by mohamedadlyy** [mieszko4/react-native-zoom-us#86]
Could not find us.zoom.sdk:commonlib:.
     Required by:
         project :app > project :react-native-zoom-meetings
   > Could not find us.zoom.sdk:mobilertc:.
     Required by:
         project :app > project :react-native-zoom-meetings

**Comment by mieszko4** [comment]
Have you tried to run a test app: https://github.com/mieszko4/react-native-zoom-us-test?

In the future please provide more details (which lib versions you use: react-native, react-native-zoom-us lib, android version, emulator/real device - see how I provide this info when testing https://github.com/mieszko4/react-native-zoom-us#testing)

**Comment by mieszko4** [comment]
You can also check newest version 6.1.1
