### ISSUE TITLE
[iOS] How to disable share screen option?

### ISSUE THREAD

**Issue by isumesh** [mieszko4/react-native-zoom-us#89]
Hi, 
Thank you for the wonderful library :D

in the `joinMeeting` api we have option to hide share button using `noShare` flag, which only works on android and not iOS ?
Also, is there a way to pass this flag in `startMeeting` api as well ?

As per the use case of my application, i only want to give them audio, video, chat and participant list functionality and nothing else. Kindly let me know how can we achieve the same using this library ?

**Comment by mieszko4** [comment]
thnx, I got some great contributors :)

I believe some of your problems should be resolved when merging https://github.com/mieszko4/react-native-zoom-us/pull/91

**Comment by mieszko4** [comment]
https://github.com/mieszko4/react-native-zoom-us/pull/91 is merged now

**Comment by mieszko4** [comment]
I took a deeper look on this. for iOS it seems there is no native settings to hide screen.
From what I see the custom UI must be implemented and then `meetingShareHidden = true` will work (https://marketplacefront.zoom.us/sdk/meeting/ios/interface_mobile_r_t_c_meeting_settings.html#af78fdb2cdb635e1a1bde5af0fce258df)

I've created a ticked for implementing iOS custom UI - https://github.com/mieszko4/react-native-zoom-us/issues/113
