### ISSUE TITLE
Setting autoConnectAudio: true in `ZoomUs.joinMeeting` does not work on iOS

### ISSUE THREAD

**Issue by alfred-soroush** [mieszko4/react-native-zoom-us#92]
Setting `autoConnectAudio: true` in `ZoomUs.joinMeeting` should join audio automatically. But does not work.

Tested with `react-native-zoom-us` 5.8.4
RN v0.64.1

**Comment by mieszko4** [comment]
I would need to verify this. Perhaps the problem is with some permissions blocking to have the auto connect.

**Comment by alfred-soroush** [comment]
I tracked this down to this line:
https://github.com/mieszko4/react-native-zoom-us/blob/master/ios/RNZoomUs.m#L293

Seems like `onMeetingError` is called before `onMeetingStateChange` with state `MobileRTCMeetingState_InMeeting` and resets `shouldAutoConnectAudio` to `nil` causing the audio connection step to skip.

**Comment by mieszko4** [comment]
:thinking: Why is `onMeetingError` called?

**Comment by mieszko4** [comment]
Please check with 6.1.1 which has newest zoom ios sdk
