### ISSUE TITLE
App is crashing after leaving meeting on iOS in production only

### ISSUE THREAD

**Issue by almahealth** [mieszko4/react-native-zoom-us#95]
Hello,

We implemented this library in our app and all is working well in dev, but when we released the app we found out that our application is crashing after leaving the meeting.

Here is the detailed crash from crashlytics:
Fatal Exception: NSRangeException
Cannot remove an observer <ZMZoomViewController 0x105119800> for the key path "contentOffset" from <ZMHorizontalTableView 0x1051fb000> because it is not registered as an observer.

And here is the logs from TestFlight:
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x18d22e754 __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1a1cf57a8 objc_exception_throw + 60 (objc-exception.mm:565)
2   Foundation                    	0x18e4d399c -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 672 (NSKeyValueObserving.m:1806)
3   Foundation                    	0x18e4d36a4 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 88 (NSKeyValueObserving.m:1910)
4   MobileRTC                     	0x10407d8f4 0x103e08000 + 2578676
5   MobileRTC                     	0x103ed04f0 0x103e08000 + 820464
6   MobileRTC                     	0x103f49658 0x103e08000 + 1316440
7   MobileRTC                     	0x103e804d8 0x103e08000 + 492760
8   MobileRTC                     	0x10404fe68 0x103e08000 + 2391656
9   CoreFoundation                	0x18d1896d4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28 (CFNotificationCenter.c:706)
10  CoreFoundation                	0x18d18967c ___CFXRegistrationPost_block_invoke + 52 (CFNotificationCenter.c:173)
11  CoreFoundation                	0x18d188be8 _CFXRegistrationPost + 440 (CFNotificationCenter.c:198)
12  CoreFoundation                	0x18d1885a8 _CFXNotificationPost + 716 (CFNotificationCenter.c:1071)
13  Foundation                    	0x18e5af778 postQueueNotifications + 424 (NSNotificationQueue.m:103)
14  CoreFoundation                	0x18d1a75e0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36 (CFRunLoop.c:1799)
15  CoreFoundation                	0x18d1a1704 __CFRunLoopDoObservers + 572 (CFRunLoop.c:1912)
16  CoreFoundation                	0x18d1a1b90 __CFRunLoopRun + 764 (CFRunLoop.c:2916)
17  CoreFoundation                	0x18d1a1360 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3242)
18  GraphicsServices              	0x1a47df734 0x1a47dc000 + 14132
19  UIKitCore                     	0x18fc1c584 -[UIApplication _run] + 1072 (UIApplication.m:3269)
20  UIKitCore                     	0x18fc21df4 UIApplicationMain + 168 (UIApplication.m:4740)

Please tell me if more information is needed

**Comment by ehabqadah** [comment]
+1

**Comment by ehabqadah** [comment]
@mieszko4 we appreciate any help or direction to resolve this?

**Comment by mieszko4** [comment]
I am not sure what the problem may be. Perhaps updating zoom-ios sdk to the newest version would resolve this for you (https://github.com/mieszko4/react-native-zoom-us/issues/109)

**Comment by mieszko4** [comment]
Please check with 6.1.1 which has newest zoom ios sdk

**Comment by praveens96** [comment]
same here. any reason only the prod iOS builds are crashing on launch?

**Comment by mieszko4** [comment]
:thinking: So is the app crashing on launch or when leaving the meeting? It seems like two different issues to me...
I haven't been able to reproduce this. Is this happening with the test app to you (https://github.com/mieszko4/react-native-zoom-us-test)?

**Comment by saqibjavaid-cc** [comment]
is there any solution for this issue?

**Comment by mieszko4** [comment]
> is there any solution for this issue?

Please provide more details about which version you tried, the logs etc.. It's been a long time since this issue was closed.
